import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
//import { getProfile } from "./images/tools";

export const sivingaMayu: ITeam[] = [
  {
    id: 16,
    grupo: "A",
    name: "Sivinga Mayu",
    logo: getLogo("Sivinga Mayu"),
    description: "Equipo de fútbol senior del grupo A",
    color: "rgb(83, 160, 243)",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          // {
          //   id: 1,
          //   name: "David",
          //   fullName: "David Quira",
          //   DNI: "62827",
          //   image: getProfile("1"),
          //   number: 11,
          //   position: "Delantero",
          // },
          // {
          //   id: 2,
          //   name: "Jose",
          //   fullName: "Jose Quira",
          //   DNI: "25865",
          //   image: getProfile("2"),
          //   number: 3,
          //   position: "Defensor",
          // },
          // {
          //   id: 3,
          //   name: "Quira",
          //   fullName: "Roberto Quira",
          //   DNI: "81588",
          //   image: getProfile("3"),
          //   number: 20,
          //   position: "Delantero",
          // },
          // {
          //   id: 4,
          //   name: "David",
          //   fullName: "David Quispe",
          //   DNI: "66248",
          //   image: getProfile("4"),
          //   number: 22,
          //   position: "Defensor",
          // },
          // {
          //   id: 5,
          //   name: "Clider",
          //   fullName: "Clider Quispe",
          //   DNI: "24467",
          //   image: getProfile("5"),
          //   number: 4,
          //   position: "Defensor",
          // },
          // {
          //   id: 6,
          //   name: "Daniel",
          //   fullName: "Daniel Quira",
          //   DNI: "79898",
          //   image: getProfile("6"),
          //   number: 10,
          //   position: "Delantero",
          // },
          // {
          //   id: 7,
          //   name: "Fede",
          //   fullName: "Federico Apaza ",
          //   DNI: "85864",
          //   image: getProfile("7"),
          //   number: 15,
          //   position: "Delantero",
          // },
          // {
          //   id: 8,
          //   name: "Sandoval",
          //   fullName: "Sandoval Quispe",
          //   DNI: "48876",
          //   image: getProfile("8"),
          //   number: 6,
          //   position: "Defensor",
          // },
          // {
          //   id: 9,
          //   name: "Vladimir",
          //   fullName: "Vladimir Santos",
          //   DNI: "92537",
          //   image: getProfile("9"),
          //   number: 17,
          //   position: "Mediocampista",
          // },
          // {
          //   id: 10,
          //   name: "Apaza",
          //   fullName: "Abrahan Apaza",
          //   DNI: "04763",
          //   image: getProfile("10"),
          //   number: 30,
          //   position: "Mediocampista",
          // },
          // {
          //   id: 11,
          //   name: "Daniel",
          //   fullName: "Daniel Santos",
          //   DNI: "71147",
          //   image: getProfile("11"),
          //   number: 8,
          //   position: "Mediocampista",
          // },
          // {
          //   id: 12,
          //   name: "Juan L.",
          //   fullName: "Jual Lopez",
          //   DNI: "70857",
          //   image: getProfile("12"),
          //   number: 9,
          //   position: "Delantero",
          // },
          // {
          //   id: 13,
          //   name: "Alexis",
          //   fullName: "Alexis Cano Quispe ",
          //   DNI: "730062",
          //   image: getProfile("13"),
          //   number: 1,
          //   position: "Portero",
          // },
          // {
          //   id: 14,
          //   name: "Ramiro",
          //   fullName: "Ramiro Quispe",
          //   DNI: "76823",
          //   image: getProfile("14"),
          //   number: 16,
          //   position: "Defensor",
          // },
          // {
          //   id: 15,
          //   name: "Joel",
          //   fullName: "Joel Cruz",
          //   DNI: "75183",
          //   image: getProfile("15"),
          //   number: 16,
          //   position: "Delantero",
          // },
          // {
          //   id: 16,
          //   name: "Jony",
          //   fullName: "Jony Cruz",
          //   DNI: "00128",
          //   image: getProfile("16"),
          //   number: 19,
          //   position: "Delantero",
          // },

          // {
          //   id: 17,
          //   name: "Alex",
          //   fullName: "Alex Apaza",
          //   DNI: "26198",
          //   image: getProfile("17"),
          //   number: 22,
          //   position: "Defensor",
          // },
          // {
          //   id: 18,
          //   name: "Leonel",
          //   fullName: "Leonel Quispe",
          //   DNI: "23753",
          //   image: getProfile("18"),
          //   number: 21,
          //   position: "Delantero",
          // },
          // {
          //   id: 19,
          //   name: "V. Quira",
          //   fullName: "Vivian Quira",
          //   DNI: "03963",
          //   image: getProfile("19"),
          //   number: 12,
          //   position: "Portero",
          // },
          // {
          //   id: 20,
          //   name: "Enzo",
          //   fullName: "Enzo Quira",
          //   DNI: "70653",
          //   image: getProfile("20"),
          //   number: 25,
          //   position: "Defensor",
          // },
        ],
      },
      // {
      //   id: 3,
      //   category: "Damas",
      //   players: [
      //     {
      //       id: 61,
      //       name: "Ale",
      //       fullName: "Gladys Quispe C.",
      //       DNI: "96726",
      //       image: getProfile("61"),
      //       number: 22,
      //       position: "Mediocampista",
      //     },
      //     {
      //       id: 62,
      //       name: "Limachi",
      //       fullName: "Limachi Noelia",
      //       DNI: "00597",
      //       image: getProfile("62"),
      //       number: 6,
      //       position: "Mediocampista",
      //     },
      //     {
      //       id: 63,
      //       name: "Quira",
      //       fullName: "Yasmin Quira C.",
      //       DNI: "85060",
      //       image: getProfile("63"),
      //       number: 3,
      //       position: "Delantera",
      //     },
      //     {
      //       id: 64,
      //       name: "Marga",
      //       fullName: "Claudia Margarita Quispe Colque",
      //       DNI: "94577",
      //       image: getProfile("64"),
      //       number: 11,
      //       position: "Delantera",
      //     },
      //     {
      //       id: 65,
      //       name: "Quira",
      //       fullName: "Carmen Quira Huarachi ",
      //       DNI: "79194",
      //       image: getProfile("65"),
      //       number: 7,
      //       position: "Mediocampista",
      //     },
      //     {
      //       id: 66,
      //       name: "Norma",
      //       fullName: "Norma Quira",
      //       DNI: "93069",
      //       image: getProfile("66"),
      //       number: 4,
      //       position: "Defensora",
      //     },
      //     {
      //       id: 67,
      //       name: "Beatriz Q.",
      //       fullName: "Elsa Beatriz Quispe C.",
      //       DNI: "96727",
      //       image: getProfile("67"),
      //       number: 2,
      //       position: "Defensora",
      //     },
      //     {
      //       id: 68,
      //       name: "Quira",
      //       fullName: "Maritza Quira Rivera ",
      //       DNI: "19277",
      //       image: getProfile("68"),
      //       number: 1,
      //       position: "Portera",
      //     },
      //     {
      //       id: 69,
      //       name: "Quira",
      //       fullName: "Soledad Quira",
      //       DNI: "50583",
      //       image: getProfile("69"),
      //       number: 21,
      //       position: "Delantera",
      //     },
      //     {
      //       id: 70,
      //       name: "Quira",
      //       fullName: "Rosmery Quira",
      //       DNI: "08841",
      //       image: getProfile("70"),
      //       number: 8,
      //       position: "Defensora",
      //     },
      //     {
      //       id: 71,
      //       name: "Tina",
      //       fullName: "Quira Cristina",
      //       DNI: "91377",
      //       image: getProfile("71"),
      //       number: 9,
      //       position: "Delantera",
      //     },
          // {
          //   id: 72,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("72"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 73,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("73"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 0,
          //   position: "",
          // },
    //     ],
    //   },
    ],
  },
];
