// import { getProfile } from "./images/tools";
import { getLogo } from "../../../tools/tools";

import type { ITeam } from "../../../types/types";

export const pucaLoma: ITeam[] = [
  {
    id: 13,
    grupo: "A",
    name: "Puca Loma",
    logo: getLogo("Puca Loma"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#48c9b0",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          // {
          //   id: 1,
          //   name: "Flores",
          //   fullName: "Alexis Flores Acuña",
          //   DNI: "95400",
          //   image: getProfile("95400"),
          //   number: 1,
          //   position: "Arquero",
          // },
          // {
          //   id: 2,
          //   name: "Rodriguez",
          //   fullName: "Nestor Ariel Rodriguez Moscoso",
          //   DNI: "98935",
          //   image: getProfile("98935"),
          //   number: 99,
          //   position: "Defensor",
          // },
          // {
          //   id: 3,
          //   name: "Alex",
          //   fullName: "Raul Alex Rodríguez Moscoso ",
          //   DNI: "93009",
          //   image: getProfile("93009"),
          //   number: 77,
          //   position: "Defensor",
          // },
          // {
          //   id: 4,
          //   name: "Luis",
          //   fullName: "Luis Camacho",
          //   DNI: "44228",
          //   image: getProfile("44228"),
          //   number: 10,
          //   position: "Delantero",
          // },
          // {
          //   id: 5,
          //   name: "Yoan",
          //   fullName: "Joan Albarado",
          //   DNI: "85777",
          //   image: getProfile("85777"),
          //   number: 7,
          //   position: "Delantero",
          // },
          // {
          //   id: 6,
          //   name: "David",
          //   fullName: "David Rodriguez",
          //   DNI: "50716",
          //   image: getProfile("50716"),
          //   number: 4,
          //   position: "Defensor",
          // },
          // {
          //   id: 7,
          //   name: "Jhony",
          //   fullName: "Jhony Moscoso Villca ",
          //   DNI: "47239",
          //   image: getProfile("47239"),
          //   number: 11,
          //   position: "Delantero",
          // },
          // {
          //   id: 8,
          //   name: "Brayan",
          //   fullName: "Brayan Moscoso Villca",
          //   DNI: "50716",
          //   image: getProfile("brayan"),
          //   number: 15,
          //   position: "Centrocampista",
          // },
          // {
          //   id: 9,
          //   name: "Clismar",
          //   fullName: "Clismar Condori",
          //   DNI: "02242",
          //   image: getProfile("23"),
          //   number: 16,
          //   position: "Mediocampista",
          // },
          // // {
          // //   id: 10,
          // //   name: "XAVI",
          // //   fullName: "Xavier M. Acuna",
          // //   DNI: "54496",
          // //   image: getProfile("xavi"),
          // //   number: 13,
          // //   position: "Centrocampista",
          // // },
          // {
          //   id: 11,
          //   name: "Rodriguez",
          //   fullName: "Jose Miguel Rodriguez Moscoso",
          //   DNI: "77061",
          //   image: getProfile("77061"),
          //   number: 28,
          //   position: "Delantero",
          // },
          // {
          //   id: 12,
          //   name: "Rog",
          //   fullName: "Roger Rodriguez Cruz ",
          //   DNI: "12428",
          //   image: getProfile("12428"),
          //   number: 18,
          //   position: "Delantero",
          // },
          // {
          //   id: 13,
          //   name: "Moscoso",
          //   fullName: "Axel Moscoso ",
          //   DNI: "17054",
          //   image: getProfile("17054"),
          //   number: 8,
          //   position: "Centrocampista",
          // },
          // {
          //   id: 14,
          //   name: "Lucas",
          //   fullName: "Lucas Moscoso",
          //   DNI: "96600",
          //   image: getProfile("96600"),
          //   number: 9,
          //   position: "Delantero",
          // },
          // {
          //   id: 15,
          //   name: "David",
          //   fullName: "David Flores",
          //   DNI: "10765",
          //   image: getProfile("10765"),
          //   number: 15,
          //   position: "Centrocampista",
          // },
          // {
          //   id: 16,
          //   name: "Clemente",
          //   fullName: "Jhonatan Clemente",
          //   DNI: "39414",
          //   image: getProfile("jhona"),
          //   number: 20,
          //   position: "Defensor",
          // },
          // {
          //   id: 17,
          //   name: "J. Clemente",
          //   fullName: "Juan Clemente",
          //   DNI: "97200",
          //   image: getProfile("97200"),
          //   number: 22,
          //   position: "Centrocampista",
          // },
          // {
          //   id: 18,
          //   name: "Delfin",
          //   fullName: "Delfin Quispe Rodríguez ",
          //   DNI: "90749",
          //   image: getProfile("90749"),
          //   number: 3,
          //   position: "Defensor",
          // },
          // {
          //   id: 19,
          //   name: "Ronald",
          //   fullName: "Ronald Ibarra",
          //   DNI: "49141",
          //   image: getProfile("49141"),
          //   number: 19,
          //   position: "Delantero",
          // },
          // // {
          // //   id: 20,
          // //   name: "Jose",
          // //   fullName: "Jose Camacho",
          // //   DNI: "26296",
          // //   image: getProfile("26296"),
          // //   number: 30,
          // //   position: "Delantero",
          // // },
          // {
          //   id: 21,
          //   name: "Miguel",
          //   fullName: "Miguel Angel Camacho Quispe",
          //   DNI: "44217",
          //   image: getProfile("44217"),
          //   number: 7,
          //   position: "Delantero",
          // },
          // {
          //   id: 22,
          //   name: "Cristian",
          //   fullName: "Cristin Moscoso Villca",
          //   DNI: "73944",
          //   image: getProfile("73944"),
          //   number: 19,
          //   position: "Delantero",
          // },
        ],
      },
    ],
  },
];
