import { getProfile } from "./images/tools";
import { getLogo } from "../../../tools/tools";

import type { ITeam } from "../../../types/types";

export const pucaLoma: ITeam[] = [
  {
    id: 2,
    grupo: "A",
    name: "Puca Loma",
    logo: getLogo("Puca Loma"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#48c9b0",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Flores",
            fullName: "Alexis Flores Acuña",
            DNI: "95400",
            image: getProfile("95400"),
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Rodriguez",
            fullName: "Nestor Ariel Rodriguez Moscoso",
            DNI: "98935",
            image: getProfile("98935"),
            number: 99,
            position: "Defensor",
          },
          {
            id: 3,
            name: "Alex",
            fullName: "Raul Alex Rodríguez Moscoso ",
            DNI: "93009",
            image: getProfile("93009"),
            number: 77,
            position: "Defensor",
          },
          {
            id: 4,
            name: "Luis",
            fullName: "Luis Camacho",
            DNI: "44228",
            image: getProfile("44228"),
            number: 10,
            position: "Delantero",
          },
          {
            id: 5,
            name: "Yoan",
            fullName: "Joan Albarado",
            DNI: "85777",
            image: getProfile("85777"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 6,
            name: "David",
            fullName: "David Rodriguez",
            DNI: "50716",
            image: getProfile("50716"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 7,
            name: "Jhony",
            fullName: "Jhony Moscoso Villca ",
            DNI: "47239",
            image: getProfile("47239"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 8,
            name: "Brayan",
            fullName: "Brayan Moscoso Villca",
            DNI: "50716",
            image: getProfile("brayan"),
            number: 15,
            position: "Centrocampista",
          },
          {
            id: 9,
            name: "Clismar",
            fullName: "Clismar Condori",
            DNI: "02242",
            image: getProfile("23"),
            number: 16,
            position: "Mediocampista",
          },
          // {
          //   id: 10,
          //   name: "XAVI",
          //   fullName: "Xavier M. Acuna",
          //   DNI: "54496",
          //   image: getProfile("xavi"),
          //   number: 13,
          //   position: "Centrocampista",
          // },
          {
            id: 11,
            name: "Rodriguez",
            fullName: "Jose Miguel Rodriguez Moscoso",
            DNI: "77061",
            image: getProfile("77061"),
            number: 28,
            position: "Delantero",
          },
          {
            id: 12,
            name: "Rog",
            fullName: "Roger Rodriguez Cruz ",
            DNI: "12428",
            image: getProfile("12428"),
            number: 18,
            position: "Delantero",
          },
          {
            id: 13,
            name: "Moscoso",
            fullName: "Axel Moscoso ",
            DNI: "17054",
            image: getProfile("17054"),
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 14,
            name: "Lucas",
            fullName: "Lucas Moscoso",
            DNI: "96600",
            image: getProfile("96600"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 15,
            name: "David",
            fullName: "David Flores",
            DNI: "10765",
            image: getProfile("10765"),
            number: 15,
            position: "Centrocampista",
          },
          {
            id: 16,
            name: "Clemente",
            fullName: "Jhonatan Clemente",
            DNI: "39414",
            image: getProfile("jhona"),
            number: 20,
            position: "Defensor",
          },
          {
            id: 17,
            name: "J. Clemente",
            fullName: "Juan Clemente",
            DNI: "97200",
            image: getProfile("97200"),
            number: 22,
            position: "Centrocampista",
          },
          {
            id: 18,
            name: "Delfin",
            fullName: "Delfin Quispe Rodríguez ",
            DNI: "90749",
            image: getProfile("90749"),
            number: 3,
            position: "Defensor",
          },
          {
            id: 19,
            name: "Ronald",
            fullName: "Ronald Ibarra",
            DNI: "49141",
            image: getProfile("49141"),
            number: 19,
            position: "Delantero",
          },
          // {
          //   id: 20,
          //   name: "Jose",
          //   fullName: "Jose Camacho",
          //   DNI: "26296",
          //   image: getProfile("26296"),
          //   number: 30,
          //   position: "Delantero",
          // },
          {
            id: 21,
            name: "Miguel",
            fullName: "Miguel Angel Camacho Quispe",
            DNI: "44217",
            image: getProfile("44217"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 22,
            name: "Cristian",
            fullName: "Cristin Moscoso Villca",
            DNI: "73944",
            image: getProfile("73944"),
            number: 19,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 30,
            name: "Siles",
            fullName: "Siles Moscoso",
            DNI: "10747",
            image: getProfile("30"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 31,
            name: "Grego",
            fullName: "Gregorio Moscoso",
            DNI: "45818",
            image: getProfile("31"),
            number: 1,
            position: "Portero",
          },
          {
            id: 32,
            name: "Xavi",
            fullName: "Javier M. Acuna",
            DNI: "54496",
            image: getProfile("xavi"),
            number: 13,
            position: "Delantero",
          },
          {
            id: 33,
            name: "Jesus",
            fullName: "JESUS QUENTA MARCO ANTONIO ",
            DNI: "62594",
            image: getProfile("33"),
            number: 3,
            position: "Defensor",
          },
          {
            id: 34,
            name: "Gabriel",
            fullName: "Gabriel Moscoso",
            DNI: "969580",
            image: getProfile("34"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 35,
            name: "Oscar",
            fullName: "Oscar Díaz Moscoso",
            DNI: "08281",
            image: getProfile("35"),
            number: 8,
            position: "Delantero",
          },
          {
            id: 36,
            name: "Fidel",
            fullName: "Fidel Condori Rodriguez",
            DNI: "81523",
            image: getProfile("36"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 37,
            name: "Carlos R.",
            fullName: "Carlos Rodriguesz Condori",
            DNI: "84767",
            image: getProfile("37"),
            number: 6,
            position: "Mediocampista",
          },
          {
            id: 38,
            name: "Camacho",
            fullName: "Julio Camacho",
            DNI: "44226",
            image: getProfile("38"),
            number: 20,
            position: "Mediocampista",
          },

          {
            id: 39,
            name: "Grober",
            fullName: "Grober Quispe Mamani",
            DNI: "89873",
            image: getProfile("39"),
            number: 4,
            position: "Defensa",
          },
          {
            id: 40,
            name: "Bayo",
            fullName: "Braulio Porco Estrada",
            DNI: "15119",
            image: getProfile("40"),
            number: 17,
            position: "Mediocampista",
          },
          {
            id: 41,
            name: "Rodriguez",
            fullName: "Roberto Rodriguez",
            DNI: "24863",
            image: getProfile("41"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 42,
            name: "Gualberto",
            fullName: "Gualberto Mamani Moscoso",
            DNI: "68575",
            image: getProfile("42"),
            number: 18,
            position: "Delantero",
          },
          {
            id: 43,
            name: "Mosqui",
            fullName: "Grover Moscoso Clemente",
            DNI: "06513",
            image: getProfile("43"),
            number: 10,
            position: "Delantero",
          },
          {
            id: 44,
            name: "Cirilo",
            fullName: "Cirilo Moscoso Mamani",
            DNI: "09905",
            image: getProfile("44"),
            number: 30,
            position: "Defensor",
          },
          {
            id: 45,
            name: "Guillermo",
            fullName: "Guillermo Rodriguez Quira",
            DNI: "01726",
            image: getProfile("45"),
            number: 22,
            position: "Defensor",
          },
          {
            id: 46,
            name: "Fran",
            fullName: "Francisco Rodriguez Quira",
            DNI: "63620",
            image: getProfile("46"),
            number: 80,
            position: "Delantero",
          },
          {
            id: 47,
            name: "Mamani",
            fullName: "Virgilio Mamani ",
            DNI: "63626",
            image: getProfile("47"),
            number: 2,
            position: "Delantero",
          },
          // {
          //   id: 37,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("37"),
          //   number: 0,
          //   position: "Delantero",
          // },
          // {
          //   id: 37,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("37"),
          //   number: 0,
          //   position: "Delantero",
          // },
          // {
          //   id: 37,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("37"),
          //   number: 0,
          //   position: "Delantero",
          // },
        ],
      },

      // damas
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "Xime",
            fullName: "Ximena Porco Rodriguez",
            DNI: "86930",
            image: getProfile("61"),
            number: 11,
            position: "Jugadora",
          },
          {
            id: 62,
            name: "Vero",
            fullName: "Veronica Porco Chirinos",
            DNI: "06845",
            image: getProfile("62"),
            number: 3,
            position: "Jugadora",
          },
          {
            id: 63,
            name: "Vane",
            fullName: "Lourdes Vanesa Camacho Quispe",
            DNI: "44232",
            image: getProfile("63"),
            number: 21,
            position: "Jugadora",
          },
          {
            id: 64,
            name: "Elida",
            fullName: "Elida Alvarado Rodriguez",
            DNI: "98562",
            image: getProfile("64"),
            number: 24,
            position: "Centrocampista",
          },
          {
            id: 65,
            name: "Nelly",
            fullName: "Nelly Albarado Rodriguez",
            DNI: "98557",
            image: getProfile("65"),
            number: 8,
            position: "Jugadora",
          },
          {
            id: 66,
            name: "Hayde",
            fullName: "Hayde Abigail Mollo",
            DNI: "89528",
            image: getProfile("66"),
            number: 19,
            position: "Jugadora",
          },
          {
            id: 67,
            name: "Alexa",
            fullName: "Norma Alexa Mamani Rodriguez",
            DNI: "97142",
            image: getProfile("67"),
            number: 30,
            position: "Jugadora",
          },
          {
            id: 68,
            name: "Karen",
            fullName: "Karen Cruz",
            DNI: "45452",
            image: getProfile("68"),
            number: 31,
            position: "Jugadora",
          },
          {
            id: 69,
            name: "Mari",
            fullName: "Marisol Moscoso",
            DNI: "92491",
            image: getProfile("69"),
            number: 1,
            position: "Jugadora",
          },
          {
            id: 70,
            name: "Loida",
            fullName: "Loida Moscoso Clemente",
            DNI: "19964",
            image: getProfile("70"),
            number: 2,
            position: "Jugadora",
          },
          {
            id: 71,
            name: "Ether",
            fullName: "Ether Rodriguez Ramos",
            DNI: "17547",
            image: getProfile("71"),
            number: 14,
            position: "Jugadora",
          },
          {
            id: 72,
            name: "Ayde",
            fullName: "Ayde Albardo Rodriguez",
            DNI: "98556",
            image: getProfile("72"),
            number: 9,
            position: "Jugadora",
          },
          {
            id: 73,
            name: "Noelia",
            fullName: "Irma Noelia Mamani Rodriguez",
            DNI: "47011",
            image: getProfile("73"),
            number: 7,
            position: "Mediocampista",
          },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 19,
          //   position: "Jugadora",
          // },
        ],
      },
      // {
      //   id: 4,
      //   category: "Infantil",
      //   players: [
      //     {
      //       id: 1,
      //       name: "Ronald Rodriguez",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 10,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 2,
      //       name: "Kevin Moscos",
      //       DNI: "23456789",
      //       image: "https://example.com/player2.jpg",
      //       number: 9,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 3,
      //       name: "Carlos Quispe",
      //       DNI: "34567890",
      //       image: "https://example.com/player3.jpg",
      //       number: 8,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 4,
      //       name: "Jugador 4",
      //       DNI: "45678901",
      //       image: "https://example.com/player4.jpg",
      //       number: 7,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 5,
      //       name: "Lian Rodriguez",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 99,
      //       position: "Delantero",
      //     },
      //   ],
      // },
    ],
  },
];
