import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";

export const miscaMayu: ITeam[] = [
  {
    id: 33,
    grupo: "A",
    name: "Miska Mayu",
    logo: getLogo("Miska Mayu"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#52be80",
    teams: [
      {
        id: 1,
        category: "Juvenil-A",
        players: [
          {
            id: 1,
            name: "Moscoso",
            fullName: "Moises Moscoso Rosario",
            DNI: "83025",
            image: getProfile("1"),
            number: 1,
            position: "Portero",
          },
          {
            id: 2,
            name: "Moscoso",
            fullName: "German Moscoso Albarado",
            DNI: "61665",
            image: getProfile("2"),
            number: 20,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Ariel",
            fullName: "Ariel Dionicio Quiñones",
            DNI: "83060",
            image: getProfile("3"),
            number: 2,
            position: "Defensor",
          },
          {
            id: 4,
            name: "Mamani",
            fullName: "Alex Mamani",
            DNI: "00599",
            image: getProfile("4"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 5,
            name: "Leandro",
            fullName: "Leandro Telao",
            DNI: "21528",
            image: getProfile("5"),
            number: 5,
            position: "Mediocampista",
          },
          {
            id: 6,
            name: "Ariel",
            fullName: "Ariel Telao",
            DNI: "68958",
            image: getProfile("6"),
            number: 3,
            position: "Centrocampista",
          },
          {
            id: 7,
            name: "David",
            fullName: "David Mamani Gomez",
            DNI: "13825",
            image: getProfile("7"),
            number: 6,
            position: "Lateral",
          },
          {
            id: 8,
            name: "Alessandro",
            fullName: "Alessandro Moscoso",
            DNI: "11976",
            image: getProfile("8"),
            number: 16,
            position: "Defensor",
          },
          {
            id: 9,
            name: "Cruz",
            fullName: "Juan Cruz",
            DNI: "16585",
            image: getProfile("9"),
            number: 10,
            position: "Delantero",
          },
          {
            id: 10,
            name: "Mati",
            fullName: "Matias Moscoso",
            DNI: "58221",
            image: getProfile("10"),
            number: 15,
            position: "Mediocampista",
          },
          {
            id: 11,
            name: "polo",
            fullName: "Diego Moscoso",
            DNI: "99327",
            image: getProfile("11"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 12,
            name: "Eddy",
            fullName: "Mamani Porcel Edilberto",
            DNI: "82035",
            image: getProfile("12"),
            number: 12,
            position: "Defensor",
          },
          {
            id: 13,
            name: "Pastor",
            fullName: "Pastor Clemente",
            DNI: "59816",
            image: getProfile("13"),
            number: 17,
            position: "Defensor",
          },
          {
            id: 14,
            name: "Wilder",
            fullName: "Fran Wilder Mollo",
            DNI: "90768",
            image: getProfile("14"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 15,
            name: "William",
            fullName: "William Mamani",
            DNI: "12359",
            image: getProfile("15"),
            number: 19,
            position: "Delantero",
          },
          {
            id: 16,
            name: "Nilton",
            fullName: "Nilton Mollo Juchani",
            DNI: "42224",
            image: getProfile("16"),
            number: 18,
            position: "Delantero",
          },
          {
            id: 17,
            name: "Moscoso",
            fullName: "Walter Moscoso",
            DNI: "95200",
            image: getProfile("17"),
            number: 20,
            position: "Delantero",
          },
          {
            id: 18,
            name: "Nahuel",
            fullName: "Nahuel Mamani",
            DNI: "50997",
            image: getProfile("18"),
            number: 17,
            position: "Delantero",
          },
          {
            id: 19,
            name: "Jose",
            fullName: "Jose Carlos Moscoso",
            DNI: "30567",
            image: getProfile("19"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 20,
            name: "Jose",
            fullName: "Jose Clemente",
            DNI: "",
            image: getProfile("20"),
            number: 15,
            position: "Delantero",
          },
        ],
      },
      // equipo B
      {
        id: 5,
        category: "Juvenil-B",
        players: [
          {
            id: 1,
            name: "Botero",
            fullName: "Gabriel Moscoso Albarado",
            DNI: "63269",
            image: getProfile("60"),
            number: 1,
            position: "Portero",
          },
          {
            id: 2,
            name: "Edgar",
            fullName: "Edgar Mamani Porcel",
            DNI: "64322",
            image: getProfile("102"),
            number: 2,
            position: "Defensor",
          },
          {
            id: 3,
            name: "German",
            fullName: "German Abdón Mamani Mollo",
            DNI: "16651",
            image: getProfile("103"),
            number: 3,
            position: "Lateral",
          },
          {
            id: 4,
            name: "Rodriguez D.",
            fullName: "Rodríguez Mamani Dilman Ivan",
            DNI: "89700",
            image: getProfile("104"),
            number: 13,
            position: "Lateral",
          },
          // {
          //   id: 5,
          //   name: "Isaac",
          //   fullName: "Isaac Mollo",
          //   DNI: "65311",
          //   image: getProfile("105"),
          //   number: 5,
          //   position: "Delantero",
          // },
          {
            id: 6,
            name: "Moscoso",
            fullName: "Ismael Alvarado Moscoso",
            DNI: "59217",
            image: getProfile("106"),
            number: 38,
            position: "Delantero",
          },
          {
            id: 7,
            name: "Clemente",
            fullName: "Clisberth Clemente Mamani",
            DNI: "45010",
            image: getProfile("107"),
            number: 8,
            position: "Mediocampista",
          },
          {
            id: 8,
            name: "Antonio",
            fullName: "Antonio Mollo Moscoso",
            DNI: "89812",
            image: getProfile("108"),
            number: 47,
            position: "Mediocampista",
          },
          {
            id: 9,
            name: "Mollo",
            fullName: "Ronaldino Mollo Huallpa",
            DNI: "53585",
            image: getProfile("109"),
            number: 6,
            position: "Defensor",
          },
          // {
          //   id: 10,
          //   name: "Richard",
          //   fullName: "Richard Rodriguez",
          //   DNI: "",
          //   image: getProfile("110"),
          //   number: 10,
          //   position: "",
          // },
          {
            id: 11,
            name: "Efrain",
            fullName: "Efrain Carmona",
            DNI: "02549",
            image: getProfile("111"),
            number: 18,
            position: "Defensor",
          },
          {
            id: 12,
            name: "Kevin",
            fullName: "Kevin Mamani",
            DNI: "80907",
            image: getProfile("112"),
            number: 24,
            position: "Lateral",
          },
          {
            id: 13,
            name: "Fabio",
            fullName: "Fabio Lisandro Mollo",
            DNI: "32284",
            image: getProfile("113"),
            number: 17,
            position: "Lateral",
          },
          {
            id: 14,
            name: "Jandel",
            fullName: "Jandel Mamani Colque",
            DNI: "84455",
            image: getProfile("114"),
            number: 14,
            position: "Delantero",
          },
          {
            id: 15,
            name: "Ezequias",
            fullName: "Ezequias Clemente",
            DNI: "20391",
            image: getProfile("115"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 16,
            name: "Brian",
            fullName: "Brian Mollo",
            DNI: "60117",
            image: getProfile("116"),
            number: 18,
            position: "Mediocampista",
          },
          {
            id: 17,
            name: "Lautaro",
            fullName: "Lautaro Clemente",
            DNI: "53023",
            image: getProfile("117"),
            number: 17,
            position: "Lateral",
          },
          {
            id: 18,
            name: "Cristopher",
            fullName: "Cristofer Mollo",
            DNI: "59751",
            image: getProfile("118"),
            number: 19,
            position: "Lateral",
          },
          {
            id: 19,
            name: "Yamil",
            fullName: "Yamil Isaias Mollo Silos",
            DNI: "63587",
            image: getProfile("119"),
            number: 18,
            position: "Mediocampista",
          },
          {
            id: 20,
            name: "Ruiz",
            fullName: "Sabino Ruiz Flores",
            DNI: "93166",
            image: getProfile("120"),
            number: 6,
            position: "Defensor",
          },
          {
            id: 21,
            name: "Clemente",
            fullName: "Clemente Antonio",
            DNI: "34443",
            image: getProfile("121"),
            number: 12,
            position: "Portero",
          },
          {
            id: 22,
            name: "Ronald",
            fullName: "Ronald  Mollo Esposo ",
            DNI: "26722",
            image: getProfile("122"),
            number: 5,
            position: "Defensor",
          },
          // {
          //   id: 23,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("123"),
          //   number: 20,
          //   position: "",
          // },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "Mary",
            fullName: "Maribel Rodriguez Quira",
            DNI: "43766",
            image: getProfile("61"),
            number: 7,
            position: "Defensa",
          },
          {
            id: 62,
            name: "Mabel",
            fullName: "Mabel Moscoso Colque",
            DNI: "31362",
            image: getProfile("62"),
            number: 11,
            position: "Delantera",
          },
          {
            id: 63,
            name: "Maribel",
            fullName: "Maribel Maldonado Mollo ",
            DNI: "62523",
            image: getProfile("63"),
            number: 8,
            position: "Mediocampista",
          },
          {
            id: 64,
            name: "Nadia",
            fullName: "Nadia Maldonado Mollo",
            DNI: "61039",
            image: getProfile("64"),
            number: 13,
            position: "Mediocampista",
          },
          {
            id: 65,
            name: "Alvarado",
            fullName: "Maira Alvarado Villca",
            DNI: "60561",
            image: getProfile("65"),
            number: 9,
            position: "Delantera",
          },
          {
            id: 66,
            name: "Jocelin",
            fullName: "Jocelin Moscoso Cruz",
            DNI: "57128",
            image: getProfile("66"),
            number: 4,
            position: "Defensa",
          },
          {
            id: 67,
            name: "Eliana",
            fullName: "Eliana Villca Mollo",
            DNI: "52570",
            image: getProfile("67"),
            number: 1,
            position: "Arquera",
          },
          {
            id: 68,
            name: "Irma",
            fullName: "Irma Ruiz Flores",
            DNI: "21341",
            image: getProfile("68"),
            number: 4,
            position: "Defensa",
          },
          {
            id: 69,
            name: "Eulalia",
            fullName: "Eulalia Moscoso Colque",
            DNI: "23888",
            image: getProfile("69"),
            number: 6,
            position: "Mediocampista",
          },
          {
            id: 70,
            name: "Gemina",
            fullName: "Gemina Mollo Santos",
            DNI: "99357",
            image: getProfile("70"),
            number: 10,
            position: "Mediocampista",
          },
          {
            id: 71,
            name: "Ruiz",
            fullName: "Esilda Ruiz",
            DNI: "71124",
            image: getProfile("71"),
            number: 11,
            position: "Delantera",
          },
          // {
          //   id: 72,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("72"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 73,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("73"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 0,
          //   position: "",
          // },
        ],
      },
    ],
  },
];
