import { getLogo } from "../../../tools/tools";
import { getProfile } from "./images/tools";

import type { ITeam } from "../../../types/types";

export const rioChico: ITeam[] = [
  {
    id: 8,
    grupo: "A",
    name: "Rio Chico",
    logo: getLogo("Rio Chico"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#aed6f1",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Ariel",
            fullName: "Ariel Mollo",
            DNI: "55122",
            image: getProfile("55122"),
            number: 1,
            position: "Portero",
          },
          {
            id: 2,
            name: "Fercho",
            fullName: "Fermando Mollo",
            DNI: "98280",
            image: getProfile("98280"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 3,
            name: "Miguelito",
            fullName: "Miguel Rojas",
            DNI: "77248",
            image: getProfile("77248"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 4,
            name: "Matias",
            fullName: "Matias Condori",
            DNI: "97322",
            image: getProfile("97322"),
            number: 3,
            position: "Defensor",
          },
          // {
          //   id: 5,
          //   name: "Gonza",
          //   fullName: "Ayrton Gonzalo Albarado Villca",
          //   DNI: "59313",
          //   image: getProfile("59313"),
          //   number: 8,
          //   position: "Defensor",
          // },
          {
            id: 22,
            name: "Rodri",
            fullName: "Rodrigo Mamani",
            DNI: "17527",
            image: getProfile("22"),
            number: 6,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Samuel",
            fullName: "Samuel Quispe Mollo",
            DNI: "97799",
            image: getProfile("97799"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 7,
            name: "Juan",
            fullName: "Nahuel Condori",
            DNI: "44951",
            image: getProfile("44951"),
            number: 5,
            position: "Defensor",
          },
          {
            id: 8,
            name: "Condori",
            fullName: "Milton Condori Cruz",
            DNI: "37738",
            image: getProfile("37738"),
            number: 16,
            position: "Defensor",
          },
          {
            id: 9,
            name: "Nahuel",
            fullName: "Nahuel Mollo",
            DNI: "56827",
            image: getProfile("56827"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 10,
            name: "Condori",
            fullName: "Iver Condori",
            DNI: "31147",
            image: getProfile("31147"),
            number: 8,
            position: "Defensor",
          },
          {
            id: 11,
            name: "Paco",
            fullName: "Juvenal Paco Condori",
            DNI: "28444",
            image: getProfile("28444"),
            number: 12,
            position: "Defensor",
          },
          {
            id: 12,
            name: "R. Soto",
            fullName: "Raimundo Soto",
            DNI: "26809",
            image: getProfile("26809"),
            number: 17,
            position: "Centrocampista",
          },
          {
            id: 13,
            name: "Edwin",
            fullName: "Edwin Colque",
            DNI: "80721",
            image: getProfile("13"),
            number: 20,
            position: "Delantero",
          },
          {
            id: 14,
            name: "Blady",
            fullName: "Bladimir Quispe Mollo ",
            DNI: "00753",
            image: getProfile("14"),
            number: 30,
            position: "Mediocampista",
          },
          // FALTAN FOTOS
          {
            id: 15,
            name: "Jose",
            fullName: "Jose Mollo",
            DNI: "41956",
            image: getProfile("15"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 16,
            name: "Elvis",
            fullName: "Elvis Mollo",
            DNI: "96633",
            image: getProfile("16"),
            number: 10,
            position: "Mediocampista",
          },
          {
            id: 17,
            name: "Ezequiel",
            fullName: "Ezequiel Mollo",
            DNI: "34815",
            image: getProfile("17"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 18,
            name: "Diego",
            fullName: "Diego Zarate",
            DNI: "90876",
            image: getProfile("18"),
            number: 19,
            position: "Delantero",
          },
          // {
          //   id: 19,
          //   name: "David",
          //   fullName: "David Otondo",
          //   DNI: "81260",
          //   image: getProfile("19"),
          //   number: 2,
          //   position: "Defensor",
          // },
          {
            id: 20,
            name: "Jhony",
            fullName: "Jhony Condori Villca",
            DNI: "87260",
            image: getProfile("20"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 21,
            name: "Kevin",
            fullName: "Kevin Condori Otondo",
            DNI: "17527",
            image: getProfile("21"),
            number: 14,
            position: "Centrocampista",
          },
        ],
      },
    ],
  },
];
