export const equipos = [
  {
    id: 1,
    grupo: "A",
    name: "Puca Loma",
    logo: "../../assets/images/logoEquipos/pucaloma.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#48c9b0",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 1,
            name: "Roberto Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 6,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Oscar Moscoso",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Siles Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Julio Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "Norma Mamani",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 5,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Juana Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Rosa Carmona",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Eunice Paco",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Sandra Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 19,
            position: "Delantero",
          },
        ],
      },
      {
        id: 4,
        category: "Infantil",
        players: [
          {
            id: 1,
            name: "Ronald Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 10,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Kevin Moscos",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Carlos Quispe",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Jugador 4",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Lian Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Delantero",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    grupo: "A",
    name: "Miska Mayu",
    logo: "../../assets/images/logoEquipos/miscamayu.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#52be80",
       teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 1,
            name: "Roberto Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 6,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Oscar Moscoso",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Siles Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Julio Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      // {
      //   id: 3,
      //   category: "Damas",
      //   players: [
      //     {
      //       id: 1,
      //       name: "Norma Mamani",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 5,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 2,
      //       name: "Juana Clemente",
      //       DNI: "23456789",
      //       image: "https://example.com/player2.jpg",
      //       number: 9,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 3,
      //       name: "Rosa Carmona",
      //       DNI: "34567890",
      //       image: "https://example.com/player3.jpg",
      //       number: 18,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 4,
      //       name: "Eunice Paco",
      //       DNI: "45678901",
      //       image: "https://example.com/player4.jpg",
      //       number: 7,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 5,
      //       name: "Sandra Rodriguez",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 19,
      //       position: "Delantero",
      //     },
      //   ],
      // },
      {
        id: 4,
        category: "Infantil",
        players: [
          {
            id: 1,
            name: "Ronald Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 10,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Kevin Moscos",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Carlos Quispe",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Jugador 4",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Lian Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Delantero",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    grupo: "A",
    name: "Punquina",
    logo: "../../assets/images/logoEquipos/punquina.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#d7dbdd",
       teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 1,
            name: "Roberto Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 6,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Oscar Moscoso",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Siles Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Julio Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "Norma Mamani",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 5,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Juana Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Rosa Carmona",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Eunice Paco",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Sandra Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 19,
            position: "Delantero",
          },
        ],
      },
      {
        id: 4,
        category: "Infantil",
        players: [
          {
            id: 1,
            name: "Ronald Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 10,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Kevin Moscos",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Carlos Quispe",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Jugador 4",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Lian Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Delantero",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    grupo: "A",
    name: "Monte Pampa",
    logo: "../../assets/images/logoEquipos/montepampa.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#f5b7b1",
        teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 1,
            name: "Roberto Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 6,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Oscar Moscoso",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Siles Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Julio Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "Norma Mamani",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 5,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Juana Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Rosa Carmona",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Eunice Paco",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Sandra Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 19,
            position: "Delantero",
          },
        ],
      },
      {
        id: 4,
        category: "Infantil",
        players: [
          {
            id: 1,
            name: "Ronald Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 10,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Kevin Moscos",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Carlos Quispe",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Jugador 4",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Lian Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Delantero",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    grupo: "A",
    name: "Rio Chico",
    logo: "../../assets/images/logoEquipos/riochico.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#aed6f1",
       teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 1,
            name: "Roberto Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 6,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Oscar Moscoso",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Siles Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Julio Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "Norma Mamani",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 5,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Juana Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Rosa Carmona",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Eunice Paco",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Sandra Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 19,
            position: "Delantero",
          },
        ],
      },
      {
        id: 4,
        category: "Infantil",
        players: [
          {
            id: 1,
            name: "Ronald Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 10,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Kevin Moscos",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Carlos Quispe",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Jugador 4",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Lian Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Delantero",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    grupo: "A",
    name: "Sivinga Mayu",
    logo: "../../assets/images/logoEquipos/sivingamay.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#99dbe7ff",
        teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      // {
      //   id: 2,
      //   category: "Senior",
      //   players: [
      //     {
      //       id: 1,
      //       name: "Roberto Rodriguez",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 6,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 2,
      //       name: "Oscar Moscoso",
      //       DNI: "23456789",
      //       image: "https://example.com/player2.jpg",
      //       number: 9,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 3,
      //       name: "Siles Moscoso",
      //       DNI: "34567890",
      //       image: "https://example.com/player3.jpg",
      //       number: 10,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 4,
      //       name: "Julio Camacho",
      //       DNI: "45678901",
      //       image: "https://example.com/player4.jpg",
      //       number: 7,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 5,
      //       name: "Xavier M. Acuna",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 13,
      //       position: "Delantero",
      //     },
      //   ],
      // },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "Norma Mamani",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 5,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Juana Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Rosa Carmona",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Eunice Paco",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Sandra Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 19,
            position: "Delantero",
          },
        ],
      },
      // {
      //   id: 4,
      //   category: "Infantil",
      //   players: [
      //     {
      //       id: 1,
      //       name: "Ronald Rodriguez",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 10,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 2,
      //       name: "Kevin Moscos",
      //       DNI: "23456789",
      //       image: "https://example.com/player2.jpg",
      //       number: 9,
      //       position: "Delantero",
      //     },
      //     {
      //       id: 3,
      //       name: "Carlos Quispe",
      //       DNI: "34567890",
      //       image: "https://example.com/player3.jpg",
      //       number: 8,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 4,
      //       name: "Jugador 4",
      //       DNI: "45678901",
      //       image: "https://example.com/player4.jpg",
      //       number: 7,
      //       position: "Centrocampista",
      //     },
      //     {
      //       id: 5,
      //       name: "Lian Rodriguez",
      //       DNI: "12345678",
      //       image: "https://example.com/player1.jpg",
      //       number: 99,
      //       position: "Delantero",
      //     },
      //   ],
      // },
    ],
  },
  {
    id: 7,
    grupo: "A",
    name: "Padcoyo",
    logo: "../../assets/images/logoEquipos/padcoyo.png",
    category: "Senior",
    description: "Equipo de fútbol senior del grupo A",
    color: "#85c1e9",
        teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cristin Flores",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 1,
            position: "Arquero",
          },
          {
            id: 2,
            name: "Nestor Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Defenza",
          },
          {
            id: 3,
            name: "Yona Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 4,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Lucas Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Luis Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 6,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 1,
            name: "Roberto Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 6,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Oscar Moscoso",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Siles Moscoso",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Julio Camacho",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Xavier M. Acuna",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 13,
            position: "Delantero",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "Norma Mamani",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 5,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Juana Clemente",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Rosa Carmona",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Eunice Paco",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Sandra Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 19,
            position: "Delantero",
          },
        ],
      },
      {
        id: 4,
        category: "Infantil",
        players: [
          {
            id: 1,
            name: "Ronald Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 10,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Kevin Moscos",
            DNI: "23456789",
            image: "https://example.com/player2.jpg",
            number: 9,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Carlos Quispe",
            DNI: "34567890",
            image: "https://example.com/player3.jpg",
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Jugador 4",
            DNI: "45678901",
            image: "https://example.com/player4.jpg",
            number: 7,
            position: "Centrocampista",
          },
          {
            id: 5,
            name: "Lian Rodriguez",
            DNI: "12345678",
            image: "https://example.com/player1.jpg",
            number: 99,
            position: "Delantero",
          },
        ],
      },
    ],
  },
];
