import { equipos } from "./equipos";

export const juvenil = [
  {
    id: 1,
    team1: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 0,
    team2: equipos[1].name,
    date: "2025-10-01",
    time: "15:00",
    location: "Stadium A",
    status: "played",
    observation: "El Arquero de  Miska Mayu no presento su tarjeta",
  },
  {
    id: 2,
    team1: equipos[2].name,
    team2: equipos[3].name,
    scorerTeam1: 4,
    scorerTeam2: 5,
    date: "2025-10-02",
    time: "16:00",
    location: "Stadium B",
    status: "played",
    observation: "",
  },
  {
    id: 3,
    team1: equipos[4].name,
    team2: equipos[5].name,
    scorerTeam1: 1,
    scorerTeam2: 4,
    date: "2025-10-03",
    time: "17:00",
    location: "Stadium C",
    status: "playing",
    observation: "",
  },
  {
    id: 4,
    team1: equipos[6].name,
    team2: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 3,
    date: "2025-10-04",
    time: "18:00",
    location: "Stadium D",
    status: "playing",
    observation: "",
  },
  {
    id: 5,
    team1: equipos[1].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-05",
    time: "19:00",
    location: "Stadium E",
    status: "willPlay",
    observation: "",
  },
  {
    id: 6,
    team1: equipos[5].name,
    team2: equipos[4].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 7,
    team1: equipos[3].name,
    team2: equipos[2].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 8,
    team1: equipos[5].name,
    team2: equipos[0].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 9,
    team1: equipos[3].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
];
export const matchesSenior = [
  {
    id: 1,
    team1: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 0,
    team2: equipos[1].name,
    date: "2025-10-01",
    time: "15:00",
    location: "Stadium A",
    status: "played",
    observation: "El Arquero de  Miska Mayu no presento su tarjeta",
  },
  {
    id: 2,
    team1: equipos[2].name,
    team2: equipos[3].name,
    scorerTeam1: 4,
    scorerTeam2: 5,
    date: "2025-10-02",
    time: "16:00",
    location: "Stadium B",
    status: "played",
    observation: "",
  },
  {
    id: 3,
    team1: equipos[4].name,
    team2: equipos[5].name,
    scorerTeam1: 1,
    scorerTeam2: 4,
    date: "2025-10-03",
    time: "17:00",
    location: "Stadium C",
    status: "playing",
    observation: "",
  },
  {
    id: 4,
    team1: equipos[6].name,
    team2: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 3,
    date: "2025-10-04",
    time: "18:00",
    location: "Stadium D",
    status: "playing",
    observation: "",
  },
  {
    id: 5,
    team1: equipos[1].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-05",
    time: "19:00",
    location: "Stadium E",
    status: "willPlay",
    observation: "",
  },
  {
    id: 6,
    team1: equipos[5].name,
    team2: equipos[4].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 7,
    team1: equipos[3].name,
    team2: equipos[2].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 8,
    team1: equipos[5].name,
    team2: equipos[0].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 9,
    team1: equipos[3].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
];
export const matchesDamas = [
  {
    id: 1,
    team1: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 0,
    team2: equipos[1].name,
    date: "2025-10-01",
    time: "15:00",
    location: "Stadium A",
    status: "played",
    observation: "El Arquero de  Miska Mayu no presento su tarjeta",
  },
  {
    id: 2,
    team1: equipos[2].name,
    team2: equipos[3].name,
    scorerTeam1: 4,
    scorerTeam2: 5,
    date: "2025-10-02",
    time: "16:00",
    location: "Stadium B",
    status: "played",
    observation: "",
  },
  {
    id: 3,
    team1: equipos[4].name,
    team2: equipos[5].name,
    scorerTeam1: 1,
    scorerTeam2: 4,
    date: "2025-10-03",
    time: "17:00",
    location: "Stadium C",
    status: "playing",
    observation: "",
  },
  {
    id: 4,
    team1: equipos[6].name,
    team2: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 3,
    date: "2025-10-04",
    time: "18:00",
    location: "Stadium D",
    status: "playing",
    observation: "",
  },
  {
    id: 5,
    team1: equipos[1].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-05",
    time: "19:00",
    location: "Stadium E",
    status: "willPlay",
    observation: "",
  },
  {
    id: 6,
    team1: equipos[5].name,
    team2: equipos[4].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 7,
    team1: equipos[3].name,
    team2: equipos[2].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 8,
    team1: equipos[5].name,
    team2: equipos[0].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 9,
    team1: equipos[3].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
];
export const matchesInfantil = [
  {
    id: 1,
    team1: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 0,
    team2: equipos[1].name,
    date: "2025-10-01",
    time: "15:00",
    location: "Stadium A",
    status: "played",
    observation: "El Arquero de  Miska Mayu no presento su tarjeta",
  },
  {
    id: 2,
    team1: equipos[2].name,
    team2: equipos[3].name,
    scorerTeam1: 4,
    scorerTeam2: 5,
    date: "2025-10-02",
    time: "16:00",
    location: "Stadium B",
    status: "played",
    observation: "",
  },
  {
    id: 3,
    team1: equipos[4].name,
    team2: equipos[5].name,
    scorerTeam1: 1,
    scorerTeam2: 4,
    date: "2025-10-03",
    time: "17:00",
    location: "Stadium C",
    status: "playing",
    observation: "",
  },
  {
    id: 4,
    team1: equipos[6].name,
    team2: equipos[0].name,
    scorerTeam1: 4,
    scorerTeam2: 3,
    date: "2025-10-04",
    time: "18:00",
    location: "Stadium D",
    status: "playing",
    observation: "",
  },
  {
    id: 5,
    team1: equipos[1].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-05",
    time: "19:00",
    location: "Stadium E",
    status: "willPlay",
    observation: "",
  },
  {
    id: 6,
    team1: equipos[5].name,
    team2: equipos[4].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 7,
    team1: equipos[3].name,
    team2: equipos[2].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 8,
    team1: equipos[5].name,
    team2: equipos[0].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
  {
    id: 9,
    team1: equipos[3].name,
    team2: equipos[1].name,
    scorerTeam1: 0,
    scorerTeam2: 0,
    date: "2025-10-06",
    time: "20:00",
    location: "Stadium F",
    status: "willPlay",
    observation: "",
  },
];
