export const positionsTable = [
  {
    team: 'Puca Loma',
    matchesPlayed: 4,
    wins: 3,
    draws: 1,
    losses: 0,
    goalsFor: 12,
    goalsAgainst: 5,
    goalDifference: 7,
    points: 10,
  },
  {
    team: 'Miska Mayu',
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
    goalsFor: 10,
    goalsAgainst: 6,
    goalDifference: 4,
    points: 7,
  },
  {
    team: 'Punquina',
    matchesPlayed: 4,
    wins: 2,
    draws: 0,
    losses: 2,
    goalsFor: 8,
    goalsAgainst: 9,
    goalDifference: -1,
    points: 6,
  },
  {
    team: 'Monte Pampa',
    matchesPlayed: 4,
    wins: 1,
    draws: 2,
    losses: 1,
    goalsFor: 5,
    goalsAgainst: 5,
    goalDifference: 0,
    points: 5,
  },
  {    team: 'Rio Chico',
    matchesPlayed: 4,
    wins: 1,
    draws: 1,
    losses: 2,
    goalsFor: 6,
    goalsAgainst: 8,
    goalDifference: -2,     
    points: 4,
  },
  {
    team: 'Sivinga Mayu',
    matchesPlayed: 4,
    wins: 1,
    draws: 0,
    losses: 3,            
    goalsFor: 4,
    goalsAgainst: 10,
    goalDifference: -6,
    points: 3,
  },
  {
    team: 'Padcoyo',
    matchesPlayed: 4,
    wins: 0,
    draws: 1,
    losses: 3,
    goalsFor: 3,        
    goalsAgainst: 11,
    goalDifference: -8,
    points: 1,
  },
  ]