import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
// import { getProfile } from "./images/tools";

export const kumuni: ITeam[] = [
  {
    id: 10,
    grupo: "A",
    name: "Kumuni",
    logo: getLogo("Kumuni"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#f17cf0ff",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          // {
          //   id: 1,
          //   name: "Cristian H.",
          //   fullName: "Cristian Huallpa Paco",
          //   DNI: "20086",
          //   image: getProfile("1"),
          //   number: 1,
          //   position: "Portero",
          // },
          // {
          //   id: 2,
          //   name: "Silvestre H.",
          //   fullName: "Silvestre Huallpa Puma",
          //   DNI: "13755",
          //   image: getProfile("2"),
          //   number: 2,
          //   position: "Defensor",
          // },
          // {
          //   id: 3,
          //   name: "Fernando",
          //   fullName: "Fernando Huallpa Puma",
          //   DNI: "73041",
          //   image: getProfile("3"),
          //   number: 3,
          //   position: "Defensa",
          // },
          // {
          //   id: 4,
          //   name: "Martinez",
          //   fullName: "Gabriel Otondo Martinez",
          //   DNI: "79464",
          //   image: getProfile("4"),
          //   number: 11,
          //   position: "Delantero",
          // },
          // {
          //   id: 5,
          //   name: "Fredy",
          //   fullName: "Fredy Albarado Calizaya",
          //   DNI: "85057",
          //   image: getProfile("5"),
          //   number: 16,
          //   position: "Defensor",
          // },
          // {
          //   id: 6,
          //   name: "Klinton",
          //   fullName: "Klinton Quira Calizaya",
          //   DNI: "67764",
          //   image: getProfile("6"),
          //   number: 30,
          //   position: "Delantero",
          // },
          // {
          //   id: 7,
          //   name: "Calizaya",
          //   fullName: "Edilson Calizaya Aguirre",
          //   DNI: "08252",
          //   image: getProfile("7"),
          //   number: 10,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 8,
          //   name: "Brian",
          //   fullName: "Brian Calizaya Aguirre",
          //   DNI: "97197",
          //   image: getProfile("8"),
          //   number: 7,
          //   position: "Delantero",
          // },
          // {
          //   id: 9,
          //   name: "Gabriel",
          //   fullName: "Gabriel Felipe Huallpa",
          //   DNI: "78537",
          //   image: getProfile("9"),
          //   number: 9,
          //   position: "Delantero",
          // },
          // {
          //   id: 10,
          //   name: "Luis M.",
          //   fullName: "Luis M. Hualla Caceres",
          //   DNI: "65528",
          //   image: getProfile("10"),
          //   number: 20,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 11,
          //   name: "Gabriel",
          //   fullName: "Gabriel Condori Calizaya",
          //   DNI: "59483",
          //   image: getProfile("11"),
          //   number: 8,
          //   position: "Lateral",
          // },
          // {
          //   id: 12,
          //   name: "Edgar",
          //   fullName: "Edgar Cayo Mamani",
          //   DNI: "04195",
          //   image: getProfile("12"),
          //   number: 18,
          //   position: "Delantero",
          // },
          // {
          //   id: 13,
          //   name: "Juan P.",
          //   fullName: "Juan Pablo Huallpa",
          //   DNI: "96619",
          //   image: getProfile("13"),
          //   number: 23,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 14,
          //   name: "Vicmar",
          //   fullName: "Vicmar Otondo Condori",
          //   DNI: "54661",
          //   image: getProfile("14"),
          //   number: 0,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 15,
          //   name: "Condori",
          //   fullName: "Raul Otondo Condori",
          //   DNI: "49437",
          //   image: getProfile("15"),
          //   number: 15,
          //   position: "Defensor",
          // },
          // {
          //   id: 16,
          //   name: "Roli",
          //   fullName: "Roli Porco Cacerez",
          //   DNI: "02202",
          //   image: getProfile("16"),
          //   number: 8,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 17,
          //   name: "Samuel",
          //   fullName: "Samuel Porco Cacerez",
          //   DNI: "12521",
          //   image: getProfile("17"),
          //   number: 5,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 18,
          //   name: "Fredy",
          //   fullName: "Fredy Condori Calizaya",
          //   DNI: "93387",
          //   image: getProfile("18"),
          //   number: 27,
          //   position: "Mediocampo",
          // },
          // {
          //   id: 19,
          //   name: "",
          //   fullName: "Alfredo Condori Calizaya",
          //   DNI: "22827",
          //   image: getProfile("19"),
          //   number: 21,
          //   position: "Defensor",
          // },
          // {
          //   id: 20,
          //   name: "",
          //   fullName: "Dani Huallpa Puma",
          //   DNI: "81099",
          //   image: getProfile("20"),
          //   number: 15,
          //   position: "Mediocampo",
          // },
        ],
      },
//   {
//   id: 3,
//   category: "Damas",
//   players: [
//     {
//       id: 61,
//       name: "Celia",
//       fullName: "Celia Caceres cruz",
//       DNI: "78643",
//       image: getProfile("61"),
//       number: 5,
//       position: "Jugadora",
//     },
//     {
//       id: 62,
//       name: "Elsa",
//       fullName: "Elsa Caseres cruz",
//       DNI: "03990",
//       image: getProfile("62"),
//       number: 6,
//       position: "Jugadora",
//     },
//     {
//       id: 63,
//       name: "Silvina",
//       fullName: "Silvina Huallpa Puma",
//       DNI: "75081",
//       image: getProfile("63"),
//       number: 7,
//       position: "Jugadora",
//     },
//     {
//       id: 64,
//       name: "Eva",
//       fullName: "Eva Colque felipe",
//       DNI: "18680",
//       image: getProfile("64"),
//       number: 8,
//       position: "Jugadora",
//     },
//     {
//       id: 65,
//       name: "Lisette",
//       fullName: "Lisette Calizaya Aguirre",
//       DNI: "19107",
//       image: getProfile("65"),
//       number: 9,
//       position: "Jugadora",
//     },
//     {
//       id: 66,
//       name: "Eulalia",
//       fullName: "Eulalia Condori Calizaya",
//       DNI: "51098",
//       image: getProfile("66"),
//       number: 10,
//       position: "Jugadora",
//     },
//     {
//       id: 67,
//       name: "Elsa",
//       fullName: "Elsa Condori Calizaya",
//       DNI: "27123",
//       image: getProfile("67"),
//       number: 11,
//       position: "Jugadora",
//     },
//     {
//       id: 68,
//       name: "Jennyfer",
//       fullName: "Jennyfer Romero Calizaya",
//       DNI: "01296",
//       image: getProfile("68"),
//       number: 12,
//       position: "Jugadora",
//     },
//     {
//       id: 69,
//       name: "Deysi",
//       fullName: "Deysi Huallpa Paco",
//       DNI: "71311",
//       image: getProfile("69"),
//       number: 13,
//       position: "Jugadora",
//     },
//     {
//       id: 70,
//       name: "Idelta",
//       fullName: "Idelta Huallpa Puma",
//       DNI: "64929",
//       image: getProfile("70"),
//       number: 14,
//       position: "Jugadora",
//     },
//     {
//       id: 71,
//       name: "Magali",
//       fullName: "Magali Huallpa Moscoso",
//       DNI: "30132",
//       image: getProfile("71"),
//       number: 15,
//       position: "Jugadora",
//     },
//     {
//       id: 72,
//       name: "Lucrecia",
//       fullName: "Lucrecia Moscoso Ibarra",
//       DNI: "75506",
//       image: getProfile("72"),
//       number: 16,
//       position: "Jugadora",
//     },
//     {
//       id: 73,
//       name: "Cintia",
//       fullName: "Cintia Huallpa Paco",
//       DNI: "53506",
//       image: getProfile("73"),
//       number: 17,
//       position: "Jugadora",
//     },
//     {
//       id: 74,
//       name: "Rosmery",
//       fullName: "Rosmery Calizaya Aquirre",
//       DNI: "52917",
//       image: getProfile("74"),
//       number: 18,
//       position: "Jugadora",
//     },
//   ],
// }

    ],
  },
];
