import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";

export const montePampa: ITeam[] = [
  {
    id: 4,
    grupo: "A",
    name: "Monte Pampa",
    logo: getLogo("Monte Pampa"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#f5b7b1",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "GEALVY",
            fullName: "Gerver Alvarado Villca ",
            DNI: "29689",
            image: getProfile("1"),
            number: 6,
            position: "Centrocampista",
          },
          {
            id: 2,
            name: "Mollo",
            fullName: "Eduardo Mollo Carmona ",
            DNI: "48496",
            image: getProfile("2"),
            number: 4,
            position: "Delantero",
          },
          {
            id: 3,
            name: "Jhoan",
            fullName: "Jhoan Alvarado Villca ",
            DNI: "95075",
            image: getProfile("3"),
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 4,
            name: "Quispe",
            fullName: "Simar Quispe Ibarra ",
            DNI: "09108",
            image: getProfile("4"),
            number: 23,
            position: "Portero",
          },
          {
            id: 5,
            name: "José Alvarado",
            fullName: "José Antonio Alvarado Condori ",
            DNI: "57303",
            image: getProfile("5"),
            number: 47,
            position: "Defensor",
          },
          {
            id: 6,
            name: "Jose",
            fullName: "Jose Luis Alvarado",
            DNI: "36930",
            image: getProfile("6"),
            number: 5,
            position: "Defensor",
          },
          {
            id: 7,
            name: "Marquitos",
            fullName: "Marcos Daniel Albarado Mamani",
            DNI: "80600",
            image: getProfile("7"),
            number: 1,
            position: "Portero",
          },
          {
            id: 8,
            name: "Betto",
            fullName: "Norberto Alvarado",
            DNI: "39226",
            image: getProfile("8"),
            number: 17,
            position: "Defensor",
          },
          {
            id: 9,
            name: "Ariel",
            fullName: "Ariel Huallpa Albarado",
            DNI: "35514",
            image: getProfile("9"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 10,
            name: "Centurio",
            fullName: "Pedro Centurio Villca ",
            DNI: "00409",
            image: getProfile("10"),
            number: 14,
            position: "Defensor",
          },
          {
            id: 11,
            name: "Gabriel",
            fullName: "Gabriel Rodríguez Mollo",
            DNI: "09173",
            image: getProfile("11"),
            number: 14,
            position: "Delantero",
          },
          {
            id: 12,
            name: "Wilder",
            fullName: "Wilder Huallpa Albarado ",
            DNI: "49414",
            image: getProfile("12"),
            number: 21,
            position: "Delantero",
          },
          {
            id: 13,
            name: "Martinez",
            fullName: "Cristian A. Martinez Mendoza ",
            DNI: "02259",
            image: getProfile("13"),
            number: 19,
            position: "Centrocampista",
          },
          {
            id: 14,
            name: "Nico",
            fullName: "Nicolas Alvarado ",
            DNI: "04882",
            image: getProfile("14"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 15,
            name: "Cristian",
            fullName: "Cristian porco",
            DNI: "01485",
            image: getProfile("15"),
            number: 20,
            position: "Defensor",
          },
          {
            id: 16,
            name: "Alex",
            fullName: "Alex Mollo Rafael",
            DNI: "99286",
            image: getProfile("16"),
            number: 10,
            position: "Delantero",
          },
          {
            id: 17,
            name: "Lionel",
            fullName: "Lionel mollo Rafael ",
            DNI: "53503",
            image: getProfile("17"),
            number: 3,
            position: "Defensor",
          },
          {
            id: 18,
            name: "Alvarado",
            fullName: "Oliver Alvarado calizaya",
            DNI: "92810",
            image: getProfile("18"),
            number: 7,
            position: "Defensor",
          },
          {
            id: 19,
            name: "Edi",
            fullName: "Edil Alvarado calizaya",
            DNI: "74457",
            image: getProfile("19"),
            number: 16,
            position: "Centrocampista",
          },
          {
            id: 20,
            name: "Wilber",
            fullName: "Wilber Albarado Moscoso",
            DNI: "31599",
            image: getProfile("20"),
            number: 4,
            position: "Defensor",
          },
        ],
      },

      // DAMAS
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "Yoselin",
            fullName: "Yoselin Clemente Mollo",
            DNI: "51397",
            image: getProfile("61"),
            number: 11,
            position: "Defensora",
          },
          {
            id: 62,
            name: "Maru",
            fullName: "María A. Mollo Rafael",
            DNI: "62269",
            image: getProfile("62"),
            number: 10,
            position: "Defensora",
          },
          {
            id: 63,
            name: "Lily",
            fullName: "Liliana Carlos Zegarra ",
            DNI: "19790",
            image: getProfile("63"),
            number: 17,
            position: "Defensora",
          },
          {
            id: 64,
            name: "Gimena",
            fullName: "Gimena Maldonado Cayo",
            DNI: "30469",
            image: getProfile("64"),
            number: 9,
            position: "Delantera",
          },
          {
            id: 65,
            name: "Eva",
            fullName: "Eva Ramos Aiza",
            DNI: "66274",
            image: getProfile("65"),
            number: 19,
            position: "Centrocampista",
          },
          {
            id: 66,
            name: "Dayana",
            fullName: "Dayana Alvarado Condori",
            DNI: "96548",
            image: getProfile("66"),
            number: 8,
            position: "Delantera",
          },
          {
            id: 67,
            name: "Sandra",
            fullName: "Sandra Centurio Villca",
            DNI: "92839",
            image: getProfile("67"),
            number: 6,
            position: "Centrocampista",
          },
          {
            id: 68,
            name: "Deicy",
            fullName: "Deicy Mamani ",
            DNI: "14278",
            image: getProfile("68"),
            number: 1,
            position: "Portera",
          },
          {
            id: 69,
            name: "Surita",
            fullName: "Soraide Albarado",
            DNI: "32634",
            image: getProfile("69"),
            number: 7,
            position: "Delantera",
          },
          {
            id: 70,
            name: "Chinita",
            fullName: "Nelvia Albarado",
            DNI: "69687",
            image: getProfile("70"),
            number: 5,
            position: "Delantera",
          },
          {
            id: 71,
            name: "Yovana",
            fullName: "Yovana Alvarado Espíritu ",
            DNI: "67918",
            image: getProfile("71"),
            number: 4,
            position: "Centrocampista",
          },
          {
            id: 72,
            name: "Gladys",
            fullName: "Gladys Alvarado Villca ",
            DNI: "61788",
            image: getProfile("72"),
            number: 2,
            position: "Centrocampista",
          },
          // {
          //   id: 73,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("73"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 0,
          //   position: "",
          // },
        ],
      },
      // SENIOR
      {
        id: 2,
        category: "Senior",
        players: [
          {
            id: 101,
            name: "Roberto",
            fullName: "Mollo Carmona Roberto ",
            DNI: "34502",
            image: getProfile("101"),
            number: 9,
            position: "Delantera",
          },
          {
            id: 102,
            name: "Alvarado",
            fullName: "Feliciano Alvarado Quispe",
            DNI: "91854",
            image: getProfile("102"),
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 103,
            name: "Paul",
            fullName: "Paulino Alvarado Quispe",
            DNI: "66652",
            image: getProfile("103"),
            number: 5,
            position: "Defensor",
          },
          {
            id: 104,
            name: "Juancho",
            fullName: "Juan Pablo Colque",
            DNI: "04151",
            image: getProfile("104"),
            number: 2,
            position: "Defensor",
          },
        ],
      },
    ],
  },
];
