import { getLogo } from "../../../tools/tools";

import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";

export const churquiPampa: ITeam[] = [
  {
    id: 6,
    grupo: "A",
    name: "Churqui Pampa",
    logo: getLogo("Churqui Pampa"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#8fcff4ff",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Cruz",
            fullName: "Fausto Cruz",
            DNI: "12060",
            image: getProfile("1"),
            number: 1,
            position: "Portero",
          },
          {
            id: 2,
            name: "Chino",
            fullName: "Cristian Cotaña Cruz",
            DNI: "27082",
            image: getProfile("2"),
            number: 44,
            position: "Centrocampista",
          },
          {
            id: 3,
            name: "Cruz",
            fullName: "Simar Cruz Mollo",
            DNI: "69108",
            image: getProfile("3"),
            number: 30,
            position: "Delantero",
          },
          {
            id: 4,
            name: " El Bicho",
            fullName: "Abel Cruz",
            DNI: "74290",
            image: getProfile("4"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 5,
            name: "Cruzito",
            fullName: "Adimir Guillermo Cruz Mollo",
            DNI: "07106",
            image: getProfile("5"),
            number: 20,
            position: "Delantero",
          },
          {
            id: 6,
            name: "Cruz",
            fullName: "Franco Nicolas Cruz Aguilar ",
            DNI: "85040",
            image: getProfile("6"),
            number: 14,
            position: "Delantero",
          },
          {
            id: 7,
            name: "Cris",
            fullName: "Cristian Aricoma Martinez",
            DNI: "90729",
            image: getProfile("7"),
            number: 12,
            position: "Delantero",
          },
          {
            id: 8,
            name: "Alexander",
            fullName: "Alexander Martinez ",
            DNI: "38775",
            image: getProfile("8"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 9,
            name: "William",
            fullName: "William Mamani Romero ",
            DNI: "34723",
            image: getProfile("9"),
            number: 33,
            position: "Delantero",
          },
          {
            id: 10,
            name: "Cruz",
            fullName: "Rulver Cruz Moscoso ",
            DNI: "08864",
            image: getProfile("10"),
            number: 19,
            position: "Centrocampista",
          },
          {
            id: 11,
            name: "Martinez",
            fullName: "Ricardo Martinez Mamani ",
            DNI: "16625",
            image: getProfile("11"),
            number: 6,
            position: "Defensor",
          },
          {
            id: 12,
            name: "J. Martinez",
            fullName: "Jose Luis Martinez ",
            DNI: "08954",
            image: getProfile("12"),
            number: 3,
            position: "Defensor",
          },
          {
            id: 13,
            name: "L. Mamani",
            fullName: "Limber Mamani",
            DNI: "42722",
            image: getProfile("13"),
            number: 24,
            position: "Centrocampista",
          },
          {
            id: 14,
            name: "N. Martinez",
            fullName: "Nuriel Martinez ",
            DNI: "41947",
            image: getProfile("14"),
            number: 17,
            position: "Mediocampista",
          },
          {
            id: 15,
            name: "J. Villca",
            fullName: "Jonathan Villca",
            DNI: "47319",
            image: getProfile("15"),
            number: 21,
            position: "Delantero",
          },
          {
            id: 16,
            name: "W. Cruz",
            fullName: "William Cruz",
            DNI: "63605",
            image: getProfile("16"),
            number: 8,
            position: "Mediocampista",
          },
          {
            id: 17,
            name: "A. Cruz",
            fullName: "Aldair Cruz",
            DNI: "45179",
            image: getProfile("17"),
            number: 10,
            position: "Delantero",
          },
          // faltan fotos
          {
            id: 18,
            name: "N. Martinez",
            fullName: "Nestor Martinez",
            DNI: "75735",
            image: getProfile("18"),
            number: 16,
            position: "Dedfensor",
          },
          {
            id: 19,
            name: "R. Martinez",
            fullName: "Raul Martinez",
            DNI: "28322",
            image: getProfile("19"),
            number: 5,
            position: "Defensor",
          },
          {
            id: 20,
            name: "A. Villca",
            fullName: "Axel Villca",
            DNI: "27865",
            image: getProfile("20"),
            number: 47,
            position: "Mediocampista",
          },
        ],
      },
      // DAMAS
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "Mabel",
            fullName: "Mabel Rodriguez Martinez ",
            DNI: "36631",
            image: getProfile("61"),
            number: 1,
            position: "Portera",
          },
          {
            id: 62,
            name: "Cintia",
            fullName: "Cintia Rodriguez Clemente ",
            DNI: "03336",
            image: getProfile("62"),
            number: 11,
            position: "Delantera",
          },
          {
            id: 63,
            name: "Virginia",
            fullName: "Virginia Velasquez",
            DNI: "29840",
            image: getProfile("63"),
            number: 7,
            position: "Delantera",
          },
          {
            id: 64,
            name: "Belinda",
            fullName: "Belinda Albarado Cruz",
            DNI: "30304",
            image: getProfile("64"),
            number: 8,
            position: "Mediocampista",
          },
          {
            id: 65,
            name: "Sonia",
            fullName: "Sonia Cruz Moscoso",
            DNI: "71359",
            image: getProfile("65"),
            number: 12,
            position: "Defensa",
          },
          {
            id: 66,
            name: "Jaqueline",
            fullName: "Jaqueline Mendoza Quispe",
            DNI: "95597310",
            image: getProfile("66"),
            number: 5,
            position: "Defensa",
          },
          {
            id: 67,
            name: "Liseth",
            fullName: "Liseth Claribel Quispe Albarado ",
            DNI: "77630",
            image: getProfile("67"),
            number: 19,
            position: "Centrocampista",
          },
          {
            id: 68,
            name: "Noemi",
            fullName: "Noemi Villca Cruz",
            DNI: "23133",
            image: getProfile("68"),
            number: 15,
            position: "Defensa",
          },
          {
            id: 69,
            name: "Flavia",
            fullName: "Flavia Moscoso Colque ",
            DNI: "41208",
            image: getProfile("69"),
            number: 32,
            position: "Centrocampista",
          },
          {
            id: 70,
            name: "Brisa",
            fullName: "Brisa Cruz Rodriguez",
            DNI: "57293",
            image: getProfile("70"),
            number: 17,
            position: "Delantera",
          },
          // {
          //   id: 71,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("71"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 72,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("72"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 73,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("73"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 0,
          //   position: "",
          // },
        ],
      },
    ],
  },
];
