import { getLogo } from "../../../tools/tools";

import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";

export const padcoyo: ITeam[] = [
  {
    id: 7,
    grupo: "A",
    name: "Padcoyo",
    logo: getLogo("Padcoyo"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#85c1e9",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Alex",
            fullName: "Alex Mamani Albarado",
            DNI: "73962",
            image: getProfile("1"),
            number: 1,
            position: "Portero",
          },
          {
            id: 2,
            name: "Ariel",
            fullName: "Ariel Villca",
            DNI: "49658",
            image: getProfile("2"),
            number: 3,
            position: "Defensa",
          },
          {
            id: 3,
            name: "Leo",
            fullName: "Leocadio Mamani",
            DNI: "19234",
            image: getProfile("3"),
            number: 30,
            position: "Defensa",
          },
          {
            id: 4,
            name: "Never",
            fullName: "Never Porco Rodriguez",
            DNI: "67536",
            image: getProfile("4"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 5,
            name: "Grover",
            fullName: "Grover Mamani",
            DNI: "49131",
            image: getProfile("5"),
            number: 4,
            position: "Defensa",
          },
          {
            id: 6,
            name: "Wilfredo",
            fullName: "Wilfredo Mamani",
            DNI: "57541",
            image: getProfile("6"),
            number: 19,
            position: "Mediocampo",
          },
          {
            id: 7,
            name: "Leandro",
            fullName: "Leandro Loayza",
            DNI: "50075",
            image: getProfile("7"),
            number: 24,
            position: "Mediocampo",
          },
          {
            id: 8,
            name: "Gilver",
            fullName: "Gilber Rivera",
            DNI: "06305",
            image: getProfile("8"),
            number: 9,
            position: "Delantero",
          },
          {
            id: 9,
            name: "Alan",
            fullName: "Alan Mamani",
            DNI: "47238",
            image: getProfile("9"),
            number: 5,
            position: "Mediocampo",
          },
          {
            id: 10,
            name: "Adalid",
            fullName: "Jose Adalid Mamani Villca",
            DNI: "02219",
            image: getProfile("10"),
            number: 22,
            position: "Delantero",
          },
          {
            id: 11,
            name: "Milton",
            fullName: "Milton Mollo Villca",
            DNI: "21393",
            image: getProfile("11"),
            number: 17,
            position: "Delantero",
          },
          {
            id: 12,
            name: "Elvis",
            fullName: "Elvis Porco",
            DNI: "99841",
            image: getProfile("12"),
            number: 21,
            position: "Delantero",
          },
          {
            id: 13,
            name: "Edson",
            fullName: "Edson Mamani A.",
            DNI: "69513",
            image: getProfile("13"),
            number: 17,
            position: "Lateral",
          },
          {
            id: 14,
            name: "Jesus",
            fullName: "Jesus Villca",
            DNI: "26956",
            image: getProfile("14"),
            number: 7,
            position: "Mediocampo",
          },
          {
            id: 15,
            name: "Poli",
            fullName: "Policarpio Porco",
            DNI: "51895",
            image: getProfile("15"),
            number: 2,
            position: "Defensa",
          },
          {
            id: 16,
            name: "Alex V.",
            fullName: "Alex Villca",
            DNI: "79067",
            image: getProfile("16"),
            number: 5,
            position: "Defensa",
          },
          {
            id: 17,
            name: "Wilson",
            fullName: "Wilson Mamani",
            DNI: "38126",
            image: getProfile("17"),
            number: 18,
            position: "Delantero",
          },
          {
            id: 18,
            name: "Alex Q.",
            fullName: "Alex Quispe",
            DNI: "20413",
            image: getProfile("18"),
            number: 6,
            position: "Defensa",
          },
          {
            id: 19,
            name: "Alex H.",
            fullName: "Alex Huchani",
            DNI: "83462",
            image: getProfile("19"),
            number: 8,
            position: "mediocampo",
          },
          {
            id: 20,
            name: "Joselo",
            fullName: "Jose Luis Villa",
            DNI: "69513",
            image: getProfile("20"),
            number: 13,
            position: "Mediocampista",
          },
        ],
      },
      // Damas
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "Gladys",
            fullName: "Gladys Claudia Porco Villca ",
            DNI: "30143",
            image: getProfile("61"),
            number: 4,
            position: "Delantera",
          },
          {
            id: 62,
            name: "Roxy",
            fullName: "Roxana Porco Villca",
            DNI: "13012",
            image: getProfile("62"),
            number: 12,
            position: "Portera",
          },
          {
            id: 63,
            name: "Roxana",
            fullName: "Roxana Villca",
            DNI: "42272",
            image: getProfile("63"),
            number: 21,
            position: "Defensora",
          },
          {
            id: 64,
            name: "Banesa",
            fullName: "Banesa Mamani",
            DNI: "43381",
            image: getProfile("64"),
            number: 7,
            position: "Mediocampista",
          },
          {
            id: 65,
            name: "Marlene",
            fullName: "Marlene Ponce",
            DNI: "24355",
            image: getProfile("65"),
            number: 2,
            position: "Defensora",
          },
          {
            id: 66,
            name: "Norma",
            fullName: "Norma Otondo Garcia",
            DNI: "57862",
            image: getProfile("66"),
            number: 3,
            position: "Centrocampista",
          },
          {
            id: 67,
            name: "Hilvia",
            fullName: "Hilvia Mollo Villca",
            DNI: "67502",
            image: getProfile("67"),
            number: 5,
            position: "Centrocampista",
          },
          {
            id: 68,
            name: "Cleofe",
            fullName: "Cleofe Mollo Villca",
            DNI: "08335",
            image: getProfile("68"),
            number: 8,
            position: "Defensora",
          },
          {
            id: 69,
            name: "Norma",
            fullName: "Norma moscoso villca",
            DNI: "12187",
            image: getProfile("69"),
            number: 13,
            position: "Delantera",
          },
          {
            id: 70,
            name: "Hilda",
            fullName: "Hilda Condori Mamani",
            DNI: "52889",
            image: getProfile("70"),
            number: 7,
            position: "Defensa",
          },
          {
            id: 71,
            name: "Villca",
            fullName: "Nayerli Villca",
            DNI: "03121",
            image: getProfile("71"),
            number: 9,
            position: "Delantera",
          },
          {
            id: 72,
            name: "Dammi",
            fullName: "Jhoselin Villca",
            DNI: "58878",
            image: getProfile("72"),
            number: 10,
            position: "Delantero",
          },
          // {
          //   id: 73,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("73"),
          //   number: 0,
          //   position: "",
          // },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 0,
          //   position: "",
          // },
        ],
      },
    ],
  },
];
