import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";

export const punquina: ITeam[] = [
  {
    id: 9,
    grupo: "A",
    name: "Punquina",
    logo: getLogo("Punquina"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#d7dbdd",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Jhon",
            fullName: "Jhonatan Villca Espinoza",
            DNI: "37178",
            image: getProfile("1"),
            number: 18,
            position: "Delantero",
          },
          {
            id: 2,
            name: "Gustavić ",
            fullName: "Gustavo Adolfo Ninaja Quispe",
            DNI: "15138",
            image: getProfile("2"),
            number: 23,
            position: "Defensor",
          },
          {
            id: 3,
            name: "Criezman",
            fullName: "Clisman Quispe",
            DNI: "85561",
            image: getProfile("3"),
            number: 66,
            position: "Defensor",
          },
          {
            id: 4,
            name: "Gustavo",
            fullName: "Gustavo Mamani Mollo ",
            DNI: "63775",
            image: getProfile("4"),
            number: 14,
            position: "Defensor",
          },
          {
            id: 5,
            name: "Braulio",
            fullName: "Braulio Quispe M.",
            DNI: "04814",
            image: getProfile("5"),
            number: 30,
            position: "Delantero",
          },
          {
            id: 6,
            name: "",
            fullName: "Limber Jaen",
            DNI: "36683",
            image: getProfile("6"),
            number: 1,
            position: "Portero",
          },
          {
            id: 7,
            name: "Rey Naldo",
            fullName: "Jose Reynaldo Mollo Porco ",
            DNI: "77023",
            image: getProfile("7"),
            number: 5,
            position: "Centrocampista",
          },
          {
            id: 8,
            name: "Gisberth",
            fullName: "Gisberth Mamani Mollo",
            DNI: "63776",
            image: getProfile("8"),
            number: 19,
            position: "Delantero",
          },
          {
            id: 9,
            name: "Brayan",
            fullName: "Brayan Mamani Mollo ",
            DNI: "63774",
            image: getProfile("9"),
            number: 28,
            position: "Defensor",
          },
          {
            id: 10,
            name: "NELSON",
            fullName: "Quispe Mollo Nelson",
            DNI: "26221",
            image: getProfile("10"),
            number: 9,
            position: "Delantero",
          },
          // {
          //   id: 11,
          //   name: "Cristian",
          //   fullName: "Angel Cristian Condori Corma ",
          //   DNI: "40340",
          //   image: getProfile("11"),
          //   number: 21,
          //   position: "Delantero",
          // },
          {
            id: 12,
            name: "Milton",
            fullName: "Milton Arnaldo Quispe Mollo",
            DNI: "31337",
            image: getProfile("12"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 13,
            name: "Wilson",
            fullName: "Emir Mamani ",
            DNI: "38431",
            image: getProfile("13"),
            number: 11,
            position: "Delantero",
          },
          {
            id: 14,
            name: "Ismo",
            fullName: "Ismael Mamani Mollo",
            DNI: "40143",
            image: getProfile("14"),
            number: 4,
            position: "Centrocampista",
          },
          {
            id: 15,
            name: "Cristian",
            fullName: "Angel Cristian Condori Corma ",
            DNI: "40340",
            image: getProfile("15"),
            number: 21,
            position: "Delantero",
          },
          {
            id: 16,
            name: "Díaz",
            fullName: "Marcial Díaz Colque ",
            DNI: "11755",
            image: getProfile("16"),
            number: 77,
            position: "Defensor",
          },
          {
            id: 17,
            name: "Alexis",
            fullName: "Alexis Mollo ",
            DNI: "98354",
            image: getProfile("17"),
            number: 12,
            position: "Centrocampista",
          },
          {
            id: 18,
            name: "ADEL",
            fullName: "Adelmar Braian Mollo Villca",
            DNI: "77180",
            image: getProfile("18"),
            number: 25,
            position: "Defensor",
          },
          {
            id: 19,
            name: "Erick",
            fullName: "Edwin Clemente.Quispe",
            DNI: "52260",
            image: getProfile("19"),
            number: 6,
            position: "Centrocampista",
          },
          {
            id: 20,
            name: "Willy",
            fullName: "Wilber Centurio Quispe",
            DNI: "31666",
            image: getProfile("20"),
            number: 10,
            position: "Mediocampista",
          },
          {
            id: 21,
            name: "Bolivar",
            fullName: "Vicmar Paco mollo ",
            DNI: "94028",
            image: getProfile("21"),
            number: 8,
            position: "Defensor",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "Elsa",
            fullName: "Eliza Mamani Mollo",
            DNI: "19713",
            image: getProfile("61"),
            number: 18,
            position: "Defensora",
          },
          {
            id: 62,
            name: "Aliz ferny",
            fullName: "Alicia Fernanda Quispe Moscoso ",
            DNI: "23041",
            image: getProfile("62"),
            number: 10,
            position: "Centrocampista",
          },
          {
            id: 63,
            name: "Claudia",
            fullName: "Claudia Roxana Quispe Moscoso ",
            DNI: "23036",
            image: getProfile("63"),
            number: 13,
            position: "Delantera",
          },
          {
            id: 64,
            name: "Mari",
            fullName: "Marizol Quispe Aiza",
            DNI: "48218",
            image: getProfile("64"),
            number: 2,
            position: "Defensa",
          },
          {
            id: 65,
            name: "Yolanda",
            fullName: "Yolanda Soto Mollo",
            DNI: "51050",
            image: getProfile("65"),
            number: 17,
            position: "Mediocampista",
          },
          {
            id: 66,
            name: "Elizabeth",
            fullName: "Elizabeth Mamani ",
            DNI: "54271",
            image: getProfile("66"),
            number: 5,
            position: "Defensora",
          },
          {
            id: 67,
            name: "Griselda",
            fullName: "Griselda Garnica Colque",
            DNI: "67497",
            image: getProfile("67"),
            number: 9,
            position: "Delantera",
          },
          {
            id: 68,
            name: "Estefi",
            fullName: "Estefanía Mollo",
            DNI: "99703",
            image: getProfile("68"),
            number: 4,
            position: "Defensa",
          },
          {
            id: 69,
            name: "Elisabet",
            fullName: "Elisabet Flores",
            DNI: "53157",
            image: getProfile("69"),
            number: 2,
            position: "Defensa",
          },
          {
            id: 70,
            name: "Anahi",
            fullName: "Nicol Anahi Condori Mollo",
            DNI: "00670",
            image: getProfile("70"),
            number: 19,
            position: "Delantera",
          },
          {
            id: 71,
            name: "Ana G.",
            fullName: "Ana G. Mamani Mollo",
            DNI: "34219",
            image: getProfile("71"),
            number: 7,
            position: "Delantera",
          },
          {
            id: 72,
            name: "Dionilda",
            fullName: "Dionilda Mollo",
            DNI: "13170",
            image: getProfile("72"),
            number: 8,
            position: "Mediocampista",
          },
          {
            id: 73,
            name: "Nora",
            fullName: "Norali Jazmin Mollo Acho ",
            DNI: "99938",
            image: getProfile("73"),
            number: 3,
            position: "Defensa",
          },
          {
            id: 74,
            name: "Albarado",
            fullName: "Zulema Sullca Albarado",
            DNI: "20336",
            image: getProfile("74"),
            number: 1,
            position: "Portera",
          },
        ],
      },
    ],
  },
];
