import { getLogo } from "../../tools/tools";
import { getProfile as getProfilePL } from "../teams/PucaLoma/images/tools";
import { getProfile as getProfileMP } from "../teams/MontePampa/images/tools";
import { getProfile as getProfileSM } from "../teams/SivingaMayu/images/tools";
import { getProfile as getProfileCP } from "../teams/ChurquiPampa/images/tools";
import { getProfile as getProfileRC } from "../teams/RioChico/images/tools";
// import { getProfile as getProfileMM} from "../teams/MiscaMayu/images/tools";

export const seniorRaw = [
  {
    id: 1,
    name: "Martin",
    fullName: "Martin Albarado",
    number: 9,
    team: "Puca Loma",
    logoteam: getLogo("Puca Loma"),
    goals: 5,
    gamesPlayed: 3,
    profile: getProfilePL("martin"),
  },
  {
    id: 2,
    name: "Roberto",
    fullName: "Roberto Mollo",
    number: 9,
    team: "Monte Pampa",
    logoteam: getLogo("Monte Pampa"),
    goals: 5,
    gamesPlayed: 3,
    profile: getProfileMP("101"),
  },
  {
    id: 3,
    name: "Fidel",
    fullName: "Fidel Quispe",
    number: 18,
    team: "Sivinga Mayu",
    logoteam: getLogo("Sivinga Mayu"),
    goals: 7,
    gamesPlayed: 3,
    profile: getProfileSM("xavi"),
  },
  {
    id: 4,
    name: "Mario",
    fullName: "Mario Quispe",
    number: 10,
    team: "Churqui Pampa",
    logoteam: getLogo("Churqui Pampa"),
    goals: 8,
    gamesPlayed: 3,
    profile: getProfileCP("xavi"),
  },
  {
    id: 5,
    name: "Rosendo",
    fullName: "Rosendo Quispe",
    number: 10,
    team: "Rio Chico",
    logoteam: getLogo("Rio Chico"),
    goals: 5,
    gamesPlayed: 3,
    profile: getProfileRC("rosendo"),
  },
    {
    id: 6,
    name: "Gabriel",
    fullName: "Gabriel Moscoso",
    number: 9,
    team: "Puca Loma 'B'",
    logoteam: getLogo("Puca Loma 'B'"),
    goals: 5,
    gamesPlayed: 1,
    profile: getProfilePL("34"),
  },
  {
    id: 7,
    name: "Siles",
    fullName: "Siles Moscoso",
    number: 7,
    team: "Puca Loma",
    logoteam: getLogo("Puca Loma"),
    goals: 10,
    gamesPlayed: 1,
    profile: getProfilePL("30"),
  },
  //   {
  //   id: 8,
  //   name: "Ruiz",
  //   fullName: "Sabino Ruiz",
  //   number: 6,
  //   team: "Miska Mayu",
  //   logoteam: getLogo("Miska Mayu"),
  //   goals: 2,
  //   gamesPlayed: 1,
  //   profile: getProfileMM("120"),
  // },
  {
    id: 9,
    name: "Mosqui",
    fullName: "Grover Moscoso",
    number: 10,
    team: "Puca Loma",
    logoteam: getLogo("Puca Loma"),
    goals: 14,
    gamesPlayed: 1,
    profile: getProfilePL("43"),
  },
  {
    id: 10,
    name: "Rojas",
    fullName: "Hipolito Rojas",
    number: 14,
    team: "Rio Chico",
    logoteam: getLogo("Rio Chico"),
    goals: 7,
    gamesPlayed: 1,
    profile: getProfilePL("rojas"),
  },
  // {
  //   id: 11,
  //   name: "Guido",
  //   fullName: "Guido Gomez",
  //   number: 14,
  //   team: "Sivinga Mayu",
  //   logoteam: getLogo("Sivinga Mayu"),
  //   goals: 4,
  //   gamesPlayed: 1,
  //   profile: getProfilePL("guido"),
  // },
  // {
  //   id: 12,
  //   name: "Daniel",
  //   fullName: "Daniel Moscoso",
  //   number: 14,
  //   team: "Miska Mayu",
  //   logoteam: getLogo("Miska Mayu"),
  //   goals: 4,
  //   gamesPlayed: 1,
  //   profile: getProfilePL("guido"),
  // },
  // {
  //   id: 13,
  //   name: "A. Villca",
  //   fullName: "Alejandro Villca",
  //   number: 11,
  //   team: "Padcoyo",
  //   logoteam: getLogo("Padcoyo"),
  //   goals: 4,
  //   gamesPlayed: 1,
  //   profile: getProfilePL("guido"),
  // },
  // {
  //   id: 14,
  //   name: "Gualberto",
  //   fullName: "Gualberto Mamani",
  //   number: 18,
  //   team: "Puca Loma",
  //   logoteam: getLogo("Puca Loma"),
  //   goals: 4,
  //   gamesPlayed: 1,
  //   profile: getProfilePL("42"),
  // },
  {
    id: 15,
    name: "Sergio",
    fullName: "Sergio Cayo",
    number: 10,
    team: "Kumuni",
    logoteam: getLogo("Kumuni"),
    goals: 6,
    gamesPlayed: 1,
    profile: getProfilePL("guido"),
  },
  {
    id: 13,
    name: "Gabino",
    fullName: "Gabino Moscoso",
    number: 10,
    team: "Churqui Pampa",
    logoteam: getLogo("Churqui Pampa"),
    goals: 5,
    gamesPlayed: 1,
    profile: getProfilePL("guido"),
  },
];
export const senior = [...seniorRaw].sort((a, b) => {
  if (b.goals !== a.goals) return b.goals - a.goals;
  return a.fullName.localeCompare(b.fullName, "es", { sensitivity: "base" });
});
