export const damas = [
  // {
  //   id: 1,
  //   team: "Puca Loma",
  //   matchesPlayed: 9,
  //   wins: 3,
  //   draws: 3,
  //   losses: 3,
  //   goalsFor: 16,
  //   goalsAgainst: 19,
  //   goalDifference: -3,
  //   points: 12,
  // },
  // {
  //   id: 2,
  //   team: "Andajaba",
  //   matchesPlayed: 9,
  //   wins: 7,
  //   draws: 1,
  //   losses: 1,
  //   goalsFor: 21,
  //   goalsAgainst: 3,
  //   goalDifference: 18,
  //   points: 22,
  // },
  // {
  //   id: 3,
  //   team: "Sivinga Mayu",
  //   matchesPlayed: 9,
  //   wins: 2,
  //   draws: 0,
  //   losses: 7,
  //   goalsFor: 11,
  //   goalsAgainst: 25,
  //   goalDifference: -14,
  //   points: 6,
  // },
  // {
  //   id: 4,
  //   team: "Monte Pampa",
  //   matchesPlayed: 9,
  //   wins: 3,
  //   draws: 3,
  //   losses: 3,
  //   goalsFor: 12,
  //   goalsAgainst: 8,
  //   goalDifference: 4,
  //   points: 12,
  // },
  // {
  //   id: 5,
  //   team: "Miska Mayu",
  //   matchesPlayed: 9,
  //   wins: 7,
  //   draws: 2,
  //   losses: 0,
  //   goalsFor: 18,
  //   goalsAgainst: 4,
  //   goalDifference: 14,
  //   points: 23,
  // },
  // {
  //   id: 6,
  //   team: "Punquina",
  //   matchesPlayed: 9,
  //   wins: 4,
  //   draws: 1,
  //   losses: 4,
  //   goalsFor: 16,
  //   goalsAgainst: 21,
  //   goalDifference: -5,
  //   points: 13,
  // },
  // {
  //   id: 7,
  //   team: "Tira Hoyo",
  //   matchesPlayed: 9,
  //   wins: 6,
  //   draws: 1,
  //   losses: 2,
  //   goalsFor: 29,
  //   goalsAgainst: 15,
  //   goalDifference: 14,
  //   points: 19,
  // },
  // {
  //   id: 8,
  //   team: "Churqui Pampa",
  //   matchesPlayed: 9,
  //   wins: 1,
  //   draws: 0,
  //   losses: 8,
  //   goalsFor: 7,
  //   goalsAgainst: 22,
  //   goalDifference: -15,
  //   points: 3,
  // },
  // {
  //   id: 9,
  //   team: "Padcoyo",
  //   matchesPlayed: 9,
  //   wins: 0,
  //   draws: 1,
  //   losses: 8,
  //   goalsFor: 11,
  //   goalsAgainst: 34,
  //   goalDifference: -23,
  //   points: 1,
  // },
  // {
  //   id: 10,
  //   team: "Kumuni",
  //   matchesPlayed: 9,
  //   wins: 6,
  //   draws: 2,
  //   losses: 1,
  //   goalsFor: 17,
  //   goalsAgainst: 4,
  //   goalDifference: 13,
  //   points: 20,
  // },
];
