import type { ITeamStanding } from "../../types/types";

export const infantil: ITeamStanding[] = [
   {
    id: 1,
    team: 'Tira Hoyo',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  {
    id: 2,
    team: 'Puca Loma',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
    {
    id: 3,
    team: 'Miska Mayu',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  {
    id: 4,
    team: 'Monte Pampa',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  {
    id: 5,
    team: 'Sivinga Mayo',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: -0,
    points: 0,
  },
  {
    id: 6,
    team: 'Churqui Pampa',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  { 
    id: 7,   
    team: 'Padcoyo',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,     
    points: 0,
  },
  {
    id: 8,
    team: 'Rio Chico',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,            
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  {
    id: 9,
    team: 'Punquina',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,        
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  {
    id: 10,
    team: 'Kumuni',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,        
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  {
    id: 11,
    team: 'Amdajava',
    matchesPlayed: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,        
    goalsAgainst: 0,
    goalDifference: 0,
    points: 0,
  },
  ]