export const juvenil = [
   {
    id: 1,
    team: 'Tira Hoyo',
    matchesPlayed: 10,
    wins: 5,
    draws: 2,
    losses: 3,
    goalsFor: 20,
    goalsAgainst: 11,
    goalDifference: 9,
    points: 17,
  },
  {
    id: 2,
    team: 'Puca Loma',
    matchesPlayed: 10,
    wins: 5,
    draws: 3,
    losses: 2,
    goalsFor: 15,
    goalsAgainst: 10,
    goalDifference: 5,
    points: 18,
  },
  {
    id: 3,
    team: 'Miska Mayu',
    matchesPlayed: 10,
    wins: 6,
    draws: 0,
    losses: 4,
    goalsFor: 38,
    goalsAgainst: 16,
    goalDifference: 22,
    points: 18,
  },
  {
    id: 4,
    team: 'Monte Pampa',
    matchesPlayed: 10,
    wins: 5,
    draws: 0,
    losses: 5,
    goalsFor: 26,
    goalsAgainst: 17,
    goalDifference: 9,
    points: 15,
  },
  {
    id: 5,
    team: 'Sivinga Mayu',
    matchesPlayed: 10,
    wins: 1,
    draws: 2,
    losses: 7,
    goalsFor: 15,
    goalsAgainst: 31,
    goalDifference: -16,
    points: 4,
  },
  {
    id: 6,
    team: 'Churqui Pampa',
    matchesPlayed: 10,
    wins: 3,
    draws: 0,
    losses: 7,
    goalsFor: 15,
    goalsAgainst: 23,
    goalDifference: -8,
    points: 9,
  },
  { 
    id: 7,   
    team: 'Padcoyo',
    matchesPlayed: 10,
    wins: 1,
    draws: 3,
    losses: 6,
    goalsFor: 10,
    goalsAgainst: 30,
    goalDifference: -2,     
    points: 6,
  },
  {
    id: 8,
    team: 'Rio Chico',
    matchesPlayed: 9,
    wins: 4,
    draws: 2,
    losses: 3,            
    goalsFor: 19,
    goalsAgainst: 14,
    goalDifference: 5,
    points: 14,
  },
  {
    id: 9,
    team: 'Punquina',
    matchesPlayed: 10,
    wins: 5,
    draws: 1,
    losses: 4,
    goalsFor: 23,        
    goalsAgainst: 20,
    goalDifference: 3,
    points: 16,
  },
  {
    id: 10,
    team: 'Kumuni',
    matchesPlayed: 9,
    wins: 8,
    draws: 0,
    losses: 1,
    goalsFor: 32,        
    goalsAgainst: 5,
    goalDifference: 27,
    points: 24,
  },
  {
    id: 11,
    team: "Miska Mayu 'B'",
    matchesPlayed: 9,
    wins: 1,
    draws: 1,
    losses: 7,
    goalsFor: 8,        
    goalsAgainst: 37,
    goalDifference: -29,
    points: 4,
  },
  ]