export const senior = [
  {
    id: 1,
    team: "Puca Loma",
    matchesPlayed: 8,
    wins: 5,
    draws: 1,
    losses: 2,
    goalsFor: 34,
    goalsAgainst: 11,
    goalDifference: 23,
    points: 16,
  },
  {
    id: 2,
    team: "Padcoyo",
    matchesPlayed: 8,
    wins: 6,
    draws: 0,
    losses: 2,
    goalsFor: 15,
    goalsAgainst: 15,
    goalDifference: 0,
    points: 18,
  },
  {
    id: 3,
    team: "Miska Mayu",
    matchesPlayed: 8,
    wins: 6,
    draws: 2,
    losses: 0,
    goalsFor: 19,
    goalsAgainst: 5,
    goalDifference: 14,
    points: 20,
  },
  {
    id: 4,
    team: "Puca Loma 'B'",
    matchesPlayed: 8,
    wins: 0,
    draws: 0,
    losses: 8,
    goalsFor: 6,
    goalsAgainst: 32,
    goalDifference: -26,
    points: 0,
  },
  {
    id: 5,
    team: "Rio Chico",
    matchesPlayed: 8,
    wins: 2,
    draws: 2,
    losses: 4,
    goalsFor: 15,
    goalsAgainst: 19,
    goalDifference: -4,
    points: 8,
  },
  {
    id: 6,
    team: "Kumuni",
    matchesPlayed: 8,
    wins: 3,
    draws: 0,
    losses: 5,
    goalsFor: 13,
    goalsAgainst: 14,
    goalDifference: -1,
    points: 9,
  },
  {
    id: 7,
    team: "Churqui Pampa",
    matchesPlayed: 8,
    wins: 4,
    draws: 1,
    losses: 3,
    goalsFor: 16,
    goalsAgainst: 14,
    goalDifference: 2,
    points: 13,
  },
  {
    id: 8,
    team: "Sivinga Mayu",
    matchesPlayed: 8,
    wins: 4,
    draws: 1,
    losses: 3,
    goalsFor: 24,
    goalsAgainst: 23,
    goalDifference: 1,
    points: 13,
  },
  {
    id: 9,
    team: "Monte Pampa",
    matchesPlayed: 8,
    wins: 2,
    draws: 1,
    losses: 5,
    goalsFor: 11,
    goalsAgainst: 19,
    goalDifference: -8,
    points: 7,
  },
];
