import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";
export const andajaba: ITeam[] = [
  {
    id: 11,
    grupo: "A",
    name: "Andajaba",
    logo: getLogo("Andajaba"),
    color: "#c7cbcaff",
    teams: [
      // {
      //   id: 1,
      //   category: "Juvenil",
      //   players: [
      // {
      //   id: 1,
      //   name: "Cristin Flores",
      //  fullName: "Carlos Flores",
      //   DNI: "12345678",
      //   image: "https://example.com/player1.jpg",
      //   number: 1,
      //   position: "Arquero",
      // },
      //   ],
      // },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 1,
            name: "D. Molina",
            fullName: "Delina Molina Martinez ",
            DNI: "16648",
            image: getProfile("1"),
            number: 12,
            position: "Jugadora",
          },
          {
            id: 2,
            name: "Ibania",
            fullName: "Ibania Condori Martinez ",
            DNI: "93944",
            image: getProfile("2"),
            number: 8,
            position: "Jugadora",
          },
          {
            id: 3,
            name: "E. Molina",
            fullName: "Ermida Molina Martinez ",
            DNI: "66093",
            image: getProfile("3"),
            number: 2,
            position: "Jugadora",
          },
          {
            id: 4,
            name: "Loyda",
            fullName: "Loyda Santos Flores ",
            DNI: "93861",
            image: getProfile("4"),
            number: 3,
            position: "Jugadora",
          },
          {
            id: 5,
            name: "Claudia",
            fullName: "Claudia Mamani Gomez ",
            DNI: "20408",
            image: getProfile("5"),
            number: 9,
            position: "Jugadora",
          },
          {
            id: 6,
            name: "Anabel",
            fullName: "Anabel Aylen Alvarado Santos ",
            DNI: "58616",
            image: getProfile("6"),
            number: 5,
            position: "Jugadora",
          },
          {
            id: 7,
            name: "Sheila",
            fullName: "Sheila Ayelen Alvarado Santos ",
            DNI: "82095",
            image: getProfile("7"),
            number: 7,
            position: "Jugadora",
          },
          {
            id: 8,
            name: "Arminda",
            fullName: "Arminda Mamani Torrez ",
            DNI: "63373",
            image: getProfile("8"),
            number: 11,
            position: "Jugadora",
          },
          {
            id: 9,
            name: "Julieta",
            fullName: "Julieta Molina Martinez ",
            DNI: "62834",
            image: getProfile("9"),
            number: 6,
            position: "Jugadora",
          },
          {
            id: 10,
            name: "Ximena",
            fullName: "Ximena Condori Carmona ",
            DNI: "52156",
            image: getProfile("10"),
            number: 10,
            position: "Jugadora",
          },
          {
            id: 11,
            name: "Claudia",
            fullName: "Claudia Avarado Calizaya",
            DNI: "85063",
            image: getProfile("11"),
            number: 18,
            position: "Jugadora",
          },
        ],
      },
    ],
  },
];
