import { getLogo } from "../../../tools/tools";
import type { ITeam } from "../../../types/types";
import { getProfile } from "./images/tools";

export const tiraHoyo: ITeam[] = [
  {
    id: 111,
    grupo: "A",
    name: "Tira Hoyo",
    logo: getLogo("Tira Hoyo"),
    description: "Equipo de fútbol senior del grupo A",
    color: "#dfa9c0c6",
    teams: [
      {
        id: 1,
        category: "Juvenil",
        players: [
          {
            id: 1,
            name: "Ferna",
            fullName: "Fernando Moscoso",
            DNI: "08283",
            image: getProfile("1"),
            number: 5,
            position: "Defensor",
          },
          {
            id: 2,
            name: "Cristian",
            fullName: "Cristian Condori",
            DNI: "75824",
            image: getProfile("2"),
            number: 9,
            position: "Centrocampista",
          },
          {
            id: 3,
            name: "Ezequiel",
            fullName: "Ezequiel Carmona",
            DNI: "87949",
            image: getProfile("3"),
            number: 18,
            position: "Delantero",
          },
          {
            id: 4,
            name: "Walter",
            fullName: "Walter Cruz ",
            DNI: "38670",
            image: getProfile("4"),
            number: 6,
            position: "Defensor",
          },
          {
            id: 5,
            name: "Eber",
            fullName: "Eber Flores Quispe ",
            DNI: "66199",
            image: getProfile("5"),
            number: 7,
            position: "Delantero",
          },
          {
            id: 6,
            name: "Neymar",
            fullName: "Neymar Flores ",
            DNI: "44627",
            image: getProfile("6"),
            number: 20,
            position: "Delantero",
          },
          {
            id: 7,
            name: "Angel",
            fullName: "Angel Torrez",
            DNI: "90390",
            image: getProfile("7"),
            number: 1,
            position: "Portero",
          },
          {
            id: 8,
            name: "Elio",
            fullName: "Elio Carmona",
            DNI: "86028",
            image: getProfile("8"),
            number: 11,
            position: "Centrocampista",
          },
          {
            id: 9,
            name: "Diego",
            fullName: "Diego Torrez",
            DNI: "74127",
            image: getProfile("9"),
            number: 4,
            position: "Defensor",
          },
          {
            id: 10,
            name: "Alejandro",
            fullName: "Alejandro Mamani",
            DNI: "45071",
            image: getProfile("10"),
            number: 3,
            position: "Defensor",
          },
          {
            id: 11,
            name: "Joni",
            fullName: "Jonathan Romero ",
            DNI: "58736",
            image: getProfile("11"),
            number: 18,
            position: "Defensor",
          },
          {
            id: 12,
            name: "Romero",
            fullName: "Romero Ruiz Gabriel ",
            DNI: "41977",
            image: getProfile("12"),
            number: 2,
            position: "Defensor",
          },
          {
            id: 13,
            name: "Chino",
            fullName: "Axel Moscoso Flores ",
            DNI: "27898",
            image: getProfile("13"),
            number: 19,
            position: "Centrocampista",
          },
          {
            id: 14,
            name: "Ale",
            fullName: "Alex Carlos Moscoso Flores ",
            DNI: "55499",
            image: getProfile("14"),
            number: 10,
            position: "Delantero",
          },
          {
            id: 15,
            name: "Vladi",
            fullName: "Vladimir Flores Colque ",
            DNI: "90081",
            image: getProfile("15"),
            number: 17,
            position: "Delantero",
          },
          {
            id: 16,
            name: "Grego",
            fullName: "Gregorio Moscoso ",
            DNI: "45818",
            image: getProfile("16"),
            number: 22,
            position: "Centrocampista",
          },
          {
            id: 17,
            name: "Fernando",
            fullName: "Fernando Romero",
            DNI: "20007",
            image: getProfile("17"),
            number: 15,
            position: "Centrocampista",
          },
          {
            id: 18,
            name: "Ronaldo",
            fullName: "Ronaldo Albarado",
            DNI: "96990",
            image: getProfile("18"),
            number: 8,
            position: "Centrocampista",
          },
          {
            id: 19,
            name: "Gabriel",
            fullName: "Gabriel Flores Colque ",
            DNI: "64192",
            image: getProfile("19"),
            number: 13,
            position: "Defensor",
          },
          {
            id: 20,
            name: "Victor",
            fullName: "Victor Rojas Heredia",
            DNI: "78590",
            image: getProfile("20"),
            number: 16,
            position: "Mediocampo",
          },
        ],
      },
      {
        id: 3,
        category: "Damas",
        players: [
          {
            id: 61,
            name: "BETY",
            fullName: "BEATRIZ MOSCOSO FLORES",
            DNI: "42333",
            image: getProfile("61"),
            number: 1,
            position: "Portera",
          },
          {
            id: 62,
            name: "Noelia",
            fullName: "Nolia Villca",
            DNI: "57104",
            image: getProfile("62"),
            number: 14,
            position: "Delantera",
          },
          {
            id: 63,
            name: "Eri",
            fullName: "ERICA JOANA MOSCOSO MAMANI",
            DNI: "21015",
            image: getProfile("63"),
            number: 5,
            position: "Defensora",
          },
          {
            id: 64,
            name: "Vero",
            fullName: "VERONICA ROMANO LENIS",
            DNI: "00645",
            image: getProfile("64"),
            number: 6,
            position: "Defensora",
          },
          {
            id: 65,
            name: "Maribel",
            fullName: "MARIBEL ROMERO",
            DNI: "93718141",
            image: getProfile("65"),
            number: 8,
            position: "Defensora",
          },
          {
            id: 66,
            name: "Maribel",
            fullName: "MARIBEL MOSCOSO",
            DNI: "38370290",
            image: getProfile("66"),
            number: 12,
            position: "Portera",
          },
          {
            id: 67,
            name: "Marisol",
            fullName: "MARISOL ROMERO MOLLO",
            DNI: "39811350",
            image: getProfile("67"),
            number: 7,
            position: "Centrocampista",
          },
           {
            id: 68,
            name: "Fany",
            fullName: "FANY ROSSY COLQUE FLORES",
            DNI: "44456",
            image: getProfile("68"),
            number: 9,
            position: "Delantera",
          },
          {
            id: 69,
            name: "Flavia",
            fullName: "FLAVIA JASMIN COLQUE FLORES",
            DNI: "11852",
            image: getProfile("69"),
            number: 11,
            position: "Delantera",
          },
          {
            id: 70,
            name: "Maria",
            fullName: "MARIA ISABEL ROCHA",
            DNI: "67330",
            image: getProfile("70"),
            number: 18,
            position: "Centrocampista",
          },
          {
            id: 71,
            name: "Claudia",
            fullName: "CLAUDIA SOLEDAD MOSCOSO FLORES",
            DNI: "64718",
            image: getProfile("71"),
            number: 3,
            position: "Delantera",
          },
          {
            id: 72,
            name: "Janet",
            fullName: "JANET JULISSA MOSCOSO FLORES",
            DNI: "53585",
            image: getProfile("72"),
            number: 13,
            position: "Delantera",
          },
          {
            id: 73,
            name: "FÁTIMA",
            fullName: "FATIMA FLORES",
            DNI: "93082",
            image: getProfile("73"),
            number: 4,
            position: "Defensora",
          },
          // {
          //   id: 74,
          //   name: "",
          //   fullName: "",
          //   DNI: "",
          //   image: getProfile("74"),
          //   number: 0,
          //   position: "",
          // },
        ],
      },
    ],
  },
];
